<%@ page language="java" import="java.util.*" contentType="text/html; charset=UTF-8" %>
<html>
<head>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script>
        var tests = [
                    {title:"	使用云凤蝶，以下哪个不是智能向导创建表格时可配置的？	", option:"	A:表格列B:批量操作C:排序D:背景色E:查询区F:全局操作G:分页器	", out:"	参考答案：D	"},
                    {title:"	云凤蝶智能向导不支持快速创建哪个表单类型？	", option:"	A:根据数据动态生成的表单项B:基础表单C:分步表单D:分组表单	", out:"	参考答案：A	"},
                    {title:"	redux数据结构	", option:"	A:栈B:图C:数组D:树	", out:"	参考答案：D	"},
                    {title:"	Antd中Select的子组件是	", option:"	A:SelectB:Select.OptionC:Select.ChildD:Select.OptGroup	", out:"	参考答案：B	"},
                    {title:"	对props和state的描述不正确的是？	", option:"	A:props一般用于父组件向子组件通信B:props在组件之间通信使用C:state一般用于组件内部的状态维护D:props主要更新组建内部的数据	", out:"	参考答案：D	"},
                    {title:"	Antd栅格间隔可以使用Row的哪个属性	", option:"	A:spanB:gutterC:pushD:offset	", out:"	参考答案：B	"},
                    {title:"	自由布局下，以下哪个不是云凤蝶支持的布局类型？	", option:"	A:适配内容B:浮动C:固定D:自适应	", out:"	参考答案：B	"},
                    {title:"	以下哪个是Antd单选组件	", option:"	A:CheckBoxB:RadioC:SelectD:Input	", out:"	参考答案：B	"},
                    {title:"	媒体查询的使用包含了什么	", option:"	A:多个可选的媒体类型，零个或多个表达式B:一个可选的媒体类型，零个或多个表达式C:一个可选的媒体类型，一个表达式D:多个可选的媒体类型，一个表达式	", out:"	参考答案：B	"},
                    {title:"	react中加载数据这类ajax请求应该放在生命周期的什么方法里面？	", option:"	A:componentWillReceivePropsB:componentWillMountC:componentWillUnmountD:componentDidMount	", out:"	参考答案：D	"},
                    {title:"	以下哪种是jsx语法？	", option:"	A:letmyTitle=&lt;h1&gt;Hello，world!&lt;/h1&gt;;B:letmyTitle=<h1>'Hello，world!'</h1>;C:letmyTitle=<h1>Hello，world!</h1>;D:letmyTitle='<h1>Hello，world!</h1>';	", out:"	参考答案：C	"},
                    {title:"	routes配置页面传参的写法正确的是？	", option:"	A:/xxx(/:yy)B:/xxx/yyC:/xxx(/yy)D:/xxx	", out:"	参考答案：A	"},
                    {title:"	react中无状态函数组件不存在的特性是？	", option:"	A:组件可以访问生命周期的方法B:组件无法访问生命周期的方法C:组件不会被实例化D:组件不能访问this对象	", out:"	参考答案：A	"},
                    {title:"	react可以由哪个周期函数来优化性能？	", option:"	A:componentWillMountB:shouldComponentUpdateC:componentWillReceivePropsD:componentWillUpdate	", out:"	参考答案：B	"},
                    {title:"	如果希望在react组件销毁时清理一些东西，例如回收定时器和取消代理时，要用到哪个方法	", option:"	A:componentWillUnMountB:componentDidUpdateC:componentDidMountD:componentWillReceiveProps	", out:"	参考答案：A	"},
                    {title:"	前端构建平台有以下哪些	", option:"	A:aoneB:basementC:金蝉D:蜻蜓	", out:"	参考答案：BCD	"},
                    {title:"	下面哪几个不是 es6 新增声明变量的()	", option:"	A:constB:letC:varD:interface	", out:"	参考答案：CD	"},
                    {title:"	react生命周期包括下面哪些	", option:"	A:componentWillUnmountB:beforeCreateC:componentWillMountD:componentDidMount	", out:"	参考答案：ACD	"},
                    {title:"	云凤蝶支持哪些插件能力？	", option:"	A:OneX金融云导航B:i18n多语言C:数据分析D:前端监控	", out:"	参考答案：ABCD	"},
                    {title:"	以下正确的前端安全通信规约是	", option:"	A:postMessage数据传输，禁止传输html和javascript字符串，防止混杂恶意攻击B:禁止Iframe应用第三方页面C:cookie中禁止存放除id，nick的其他敏感信息，包括但不限于phonenumber，password，realnameD:数据在渲染到页面上时，需要对数据进行安全转义，防止恶意DOMXSS攻击	", out:"	参考答案：ABCD	"},
                    {title:"	属于dva中modul的api是哪些	", option:"	A:StateB:ReducerC:SubscriptionD:Effect	", out:"	参考答案：ABCD	"},
                    {title:"	JS的内置函数	", option:"	A:MathB:FunctionC:ObjectD:JSON	", out:"	参考答案：BC	"},
                    {title:"	可以使用Babel工具将ES6 代码先转为 ES5	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	Antd的InputNumber组件是当需要获取标准数值时使用	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	antd的List组件可承载文字、列表、图片、段落，常用于后台数据展示页面	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	antd的轮播组件Carousel在有轮播图片的场景时可以使用	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	CSS编码规约中，对于使用到小数的情况，省略前边的0	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	Effect 被称为副作用，在我们的应用中，最常见的就是异步操作	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	Antd中Form.create 包装的组件将会自带 this.props.form 属性	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	Dva model中put不仅可以调用reduers 对象中的方法，也可以调用effects里面的函数	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	componentWillUpdate这个生命周期不能立马设置setState，否则会出现循环调用	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	如果组件是具有状态（state）或生命周期方法，则用函数组件（function component）？	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	react父组件传给子组件的props变化时会调用子组件的哪个方法	", option:"	A:componentWillReceivePropsB:componentWillUnmountC:componentDidMountD:componentDidUpdate	", out:"	参考答案：A	"},
                    {title:"	const和let区别描述错误的是？	", option:"	A:使用const声明的是常量，在后面出现的代码中不能再修改该常量的值。B:使用let声明的变量，其作用域为该语句所在的代码块内，不存在变量提升；C:const声明的变量只可以在声明时赋值，不可随意修改D:使用const声明的是变量，在后面出现的代码中可以修改该常量的值。	", out:"	参考答案：D	"},
                    {title:"	React组件内部通过哪个对象获取参数	", option:"	A:this.stateB:this.paramC:this.propsD:this.form	", out:"	参考答案：C	"},
                    {title:"	以下符合react对class的命名规范的是	", option:"	A:my_titleB:myTitleC:mytitleD:MyTitle	", out:"	参考答案：D	"},
                    {title:"	Flex 布局是基于多少栅格来定义的	", option:"	A:18B:16C:24D:36	", out:"	参考答案：C	"},
                    {title:"	以下哪个是ES6新增的原始数据类型	", option:"	A:SymbolB:NumberC:nullD:Object	", out:"	参考答案：A	"},
                    {title:"	传递给setState的第二个参数是什么？	", option:"	A:数组B:字符串C:回调函数D:布尔值	", out:"	参考答案：C	"},
                    {title:"	使用云凤蝶，如果需要嵌入到已有的 procode （例如 umi ） 项目中，需要用哪种方案？	", option:"	A:OneXB:BigFlyC:云凤蝶托管服务D:反向代理	", out:"	参考答案：B	"},
                    {title:"	在生命周期中的哪一步你应该发起 AJAX 请求？	", option:"	A:componentDidMountB:renderC:componentWillUpdateD:shouldComponentUpdate	", out:"	参考答案：A	"},
                    {title:"	云凤蝶自由布局下，下列哪个关于类型的设置描述是错误的？	", option:"	A:如果宽度设置固定，当父容器宽度发生变化时，宽度保持不变B:如果父容器设置适配内容，子元素设置为自适应，子元素会随父元素变化C:如果宽度设置适配内容，当内容发生变化时，宽度随内容变化D:如果宽度设置自适应，当父容器宽度发生变化时，宽度随父容器变化	", out:"	参考答案：B	"},
                    {title:"	云凤蝶可以导入 NPM 组件包，以下哪个是错误的？	", option:"	A:NPM包需要手动升级才会更新版本B:TypeScript定义的属性定义会被自动识别C:NPM包没有TypeScript定义，包内组件也可被识别D:只要支持style、className，并且有默认导出的ReactNPM包都可导入	", out:"	参考答案：C	"},
                    {title:"	如果确定组件的 props 或者 state 的改变不需要重新渲染，可以通过哪个生命周期的方法来阻止组件的重新渲染？	", option:"	A:componentWillMountB:shouldComponentUpdateC:componentWillReceivePropsD:componentWillUpdate	", out:"	参考答案：B	"},
                    {title:"	云凤蝶自由布局下，下列哪个不能达到预期？	", option:"	A:宽度设置自适应，左右间距设置自适应B:宽度设置自适应，左右间距设置固定C:高度设置自适应，上下间距固定D:两个组件设置宽度固定，左侧组件左间距固定，右间距自适应；右侧组件左间距自适应，右间距固定	", out:"	参考答案：A	"},
                    {title:"	以下哪些是css的样式引入	", option:"	A:外部样式B:行内样式C:内部样式D:行外样式	", out:"	参考答案：ABC	"},
                    {title:"	关于移动端300ms延迟响应，说法正确的是？	", option:"	A:可以通过引入fastclick解决300ms延迟B:通过完全禁用缩放，可以达到去掉点击延迟的目的C:300ms的延迟响应的原因是，由于区分单击事件和双击屏幕缩放的历史原因造成的D:使用zepto的tap事件能较好解决点击延迟	", out:"	参考答案：ABCD	"},
                    {title:"	antd的Notification提醒组件经常用于以下哪些情况	", option:"	A:较为复杂的通知内容B:带有交互的通知，给出用户下一步的行动点C:系统主动推送	", out:"	参考答案：ABC	"},
                    {title:"	在云凤蝶如果有多个只读字段展示的例如详情页的需求，可以使用哪些方式实现？	", option:"	A:使用描述列表组件B:使用多个文本组件手动排版C:通过代码添加组件元素D:通过代码修改DOM节点	", out:"	参考答案：AB	"},
                    {title:"	不换行必须设置	", option:"	A:word-breakB:letter-spacingC:white-spaceD:word-spacing	", out:"	参考答案：AC	"},
                    {title:"	JavaScript中如何检测a变量是一个数组，a=[1，2，3]	", option:"	A:a.length>0B:Array.isArray(a)C:typeof(a)==='object'D:ainstanceofArray	", out:"	参考答案：BD	"},
                    {title:"	JavaScript 中常见设计模式	", option:"	A:迭代器模式B:策略模式C:单例模式D:代理模式	", out:"	参考答案：ABCD	"},
                    {title:"	antd的Popover气泡卡片，当目标元素有进一步的描述和相关操作时，可以收纳到卡片中，根据用户的操作行为进行展现。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	安装antd的指令是npm install antd --save 吗	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	Babel 用来在浏览器转换 JSX 语法	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	react的componentWillReceiveProps 方法会在render之后执行	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	dva的model中从state中获取数据用 select 函数？	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	使用visibility:hidden属性后HTML元素（对象）仅仅是在视觉上看不见，而它所占据的空间位置仍然存在？	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	在组件需要包含内部状态或者使用到生命周期函数的时候使用 Class Component？	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	云凤蝶支持哪种数据连接方式？	", option:"	A:TRB:以上都是C:数据集D:HTTP	", out:"	参考答案：B	"},
                    {title:"	以下哪项不是let、var和const的区别？	", option:"	A:const声明的变量只可以在声明时赋值，不可随意修改B:let方式声明的变量在声明之前调用会报错C:let命令不存在变量提升D:let方式声明的变量不可以修改	", out:"	参考答案：D	"},
                    {title:"	在云凤蝶，什么情况下反向代理后，访问页面会显示 Not Found 或 404？	", option:"	A:忘记部署B:以上都是C:页面路由与后端不匹配D:后端配置错误	", out:"	参考答案：B	"},
                    {title:"	dva中数据流向非常明确，通过 dispatch 发起一个 action的时候，如果是同步行为会直接通过（）改变State	", option:"	A:AndtB:EffectsC:ReducersD:React	", out:"	参考答案：C	"},
                    {title:"	redux的三大原则错误的是 ？	", option:"	A:State是只读的B:使用纯函数来执行修改C:单向数据流D:单一数据源	", out:"	参考答案：C	"},
                    {title:"	以下哪个关于代码逻辑的描述是错误的？	", option:"	A:在云凤蝶中可以通过编写代码直接增删组件B:数据绑定可以是一个表达式也可以是一个函数C:在云凤蝶中数据来源分为全局数据、导航栏数据、页面数据、组件数据、上下文数据D:云凤蝶支持单选绑定和双向绑定两种数据绑定方式	", out:"	参考答案：A	"},
                    {title:"	react怎么获取store数据	", option:"	A:updateB:connetC:dispacthD:reducer	", out:"	参考答案：B	"},
                    {title:"	以下哪个jsx写法是正确的	", option:"	A:{2>1?2大于1:1大于2}B:className=”BlueColor”C:style={{color:blue，textAlign:center}}D:(2>1?2大于1:1大于2)E:style=”color:blue;text-align:center”	", out:"	参考答案：ABC	"},
                    {title:"	学习React之前需要掌握哪些技术	", option:"	A:JAVAB:CSSC:HTMLD:JavaScript	", out:"	参考答案：BCD	"},
                    {title:"	使用云凤蝶时，如果页面中有一部分组件、区域想在其他应用中使用有哪些方式？	", option:"	A:目标应用添加引用当前应用B:选中页面中组件用快捷键复制粘贴C:对页面右键复制到，然后选择目标应用D:创建一个资产包将组件复制到资产包，并在其他应用中引用资产包	", out:"	参考答案：BCD	"},
                    {title:"	下面哪些方案可以用来管理组件之间的共享状态	", option:"	A:dvaB:reduxC:stateD:状态提升	", out:"	参考答案：ABD	"},
                    {title:"	组件的内部状态对象用this.setState方法来重置	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	react的componentDidMount 方法会在render方法之后执行	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	antd的Collapse折叠组件可以折叠/展开内容区域	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	antd的Tooltip文字提示组件鼠标移入则显示提示，移出消失。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	网络请求状态码“200  (from disk cache)” 比“304”请求速度慢	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	跨域的原因是浏览器的同源策略	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	dva的model中触发action用put函数？	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	使用云凤蝶时，导入的 NPM 不可以调整哪个配置？	", option:"	A:属性配置B:尺寸可选配置C:父子组件设置D:动效配置	", out:"	参考答案：D	"},
                    {title:"	下列哪种CSS样式定义的方式拥有最高的优先级？	", option:"	A:导入B:嵌入C:行内D:链接	", out:"	参考答案：C	"},
                    {title:"	下列的HTML中哪个可以产生文本区？	", option:"	A:<inputtype=\"textarea\">B:<inputtype=\"textbox\">C:<textarea></textarea>D:<textarea>	", out:"	参考答案：C	"},
                    {title:"	以下哪项对apply、call和bind的理解不正确？	", option:"	A:三者都可以把一个函数应用到其他对象上B:apply和call的区别是apply接受数组作为参数，而call是接受逗号分隔的无限多个参数列表C:bind是返回了一个新的函数，并且立即执行D:call、apply是修改函数的作用域（修改this指向），并且立即执行	", out:"	参考答案：C	"},
                    {title:"	关于react中render方法中jsx的内联样式style，以下格式正确的是	", option:"	A:style={'marginTop:10px'}B:style={{marginTop:'10px'}}C:style={marginTop:'10px'}D:style={{'marginTop:10px'}}	", out:"	参考答案：B	"},
                    {title:"	关于react的生命周期的理解不正确的是？	", option:"	A:componentWillReceiveProps方法会在render之后执行B:componentWillUnmount表示组件卸载前的状态C:componentWillMount方法会在render方法之前执行D:componentDidMount方法会在render方法之后执行	", out:"	参考答案：A	"},
                    {title:"	box-sizing常用的属性有哪些？	", option:"	A:inherit-boxB:inheritC:content-boxD:border-box	", out:"	参考答案：BCD	"},
                    {title:"	display有哪些值？	", option:"	A:inlineB:noneC:blockD:list-itemE:inline-block	", out:"	参考答案：ABCDE	"},
                    {title:"	ES6新特性	", option:"	A:let，constB:Promise对象C:字符串的扩展D:变量的解构赋值	", out:"	参考答案：ABCD	"},
                    {title:"	let myTitle = <p>{'Hello ' + 'World'}</p> 这是jsx语法	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	当ERROR错误发生时，已经影响了用户的正常访问	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	antd的Tabs标签页组件提供平级的区域将大块内容进行收纳和展现，保持界面整洁	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	antd的Upload上传组件，可以在提交到服务器之前调用beforeUpload做文件校验	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	JS的typeof返回数据类型:string、number、object、boolean、function	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	Antd的Slider滑动输入条是在当用户需要在数值区间/自定义区间内进行选择时使用	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	dva的dispatch是一个函数方法，用来将 Action 发送给 props	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	dva的model中调用异步逻辑用call函数？	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	以下哪个是antd的分页组件	", option:"	A:PaginationB:TableC:TreeSelectD:Steps	", out:"	参考答案：A	"},
                    {title:"	React组件中必须要有的方法是	", option:"	A:beforeCreateB:componentWillMountC:onSubmitD:render	", out:"	参考答案：D	"},
                    {title:"	CSS编码规约推荐缩进要用几个空格	", option:"	A:2B:1C:4D:3	", out:"	参考答案：A	"},
                    {title:"	当通过遍历生成react元素时需要加上什么属性	", option:"	A:keyB:targetC:labelD:id	", out:"	参考答案：A	"},
                    {title:"	以下对于箭头函数的理解错误的是？	", option:"	A:函数对象中的call、apply、bind三个方法，无法\"覆盖\"箭头函数中的this值B:箭头函数没有普通函数有的隐藏arguments对象。C:箭头函数不属于普通的function，所以没有独立的上下文D:箭头函数能当作generators使用	", out:"	参考答案：D	"},
                    {title:"	箭头函数和匿名函数的理解不正确得是？	", option:"	A:箭头函数可以当作构造函数B:箭头函数不可以当作构造函数C:箭头函数不可以使用arguments对象D:箭头函数体内的this对象，就是定义时所在的对象，而不是使用时所在的对象。	", out:"	参考答案：A	"},
                    {title:"	关于云凤蝶中的弹性布局，下列哪个描述是错误的？	", option:"	A:弹性布局下，当父容器宽度或高度是适配内容时折行不生效B:弹性布局可以通过设置内外边距控制组件间距C:弹性布局下不可通过拖拽调整组件位置D:弹性布局支持横向和纵向排列	", out:"	参考答案：C	"},
                    {title:"	以下哪些组件能在antd中找到	", option:"	A:AlertB:AutoCompleteC:TooltipD:Cascader	", out:"	参考答案：ABCD	"},
                    {title:"	以下哪些是react的特点？	", option:"	A:灵活B:复用性好C:复杂D:高效	", out:"	参考答案：ABD	"},
                    {title:"	声明react组件的方式有几种	", option:"	A:React.createElementB:React.createClassC:React.ComponentD:无状态函数式组件	", out:"	参考答案：BCD	"},
                    {title:"	关于antd的表单元素的defaultValue和value，以下说法正确的是	", option:"	A:value值可以通过setState重新渲染B:如果想要动态改变表单的值，可以用valueC:一般改变value的值要绑定onChange事件D:defaultValue是默认值，初始化只渲染一次，后续如果值再改变，它是不改变的	", out:"	参考答案：ABCD	"},
                    {title:"	react组件间传值方式	", option:"	A:state状态传值B:callback回调传值C:代理传值D:props属性传值	", out:"	参考答案：BD	"},
                    {title:"	使用dva-loading时，要先import createLoading from 'dva-loading';然后app.use(createLoading());这样就可以通过state来处理loading了	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	antd的轮播组件Carousel除了轮播图片还可以轮播卡片Card	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	Antd的Checkbox组件在一组可选项中进行多项选择时使用	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	Antd的Switch开关组件需要表示开关状态/两种状态之间的切换时使用	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	新建组件推荐继承React.Component，这样的话绑定事件的方法就需要bind(this)或者用箭头函数才行，不然方法中的this指向是undefined	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	Antd中Button组件点击事件触发的方法是	", option:"	A:onChangeB:onSubmitC:onClearD:onClick	", out:"	参考答案：D	"},
                    {title:"	React组件文件最好使用以下哪种扩展名	", option:"	A:.jsB:.jssC:.jsxxD:.jsx	", out:"	参考答案：D	"},
                    {title:"	dva中数据流向非常明确，通过 dispatch 发起一个 action的时候，如果是异步行为会先触发（）， 然后流向 Reducers 最终改变 State	", option:"	A:ReactB:ReducersC:AndtD:Effects	", out:"	参考答案：D	"},
                    {title:"	比较常用的移动端设配方案是	", option:"	A:媒体查询B:同构比例，缩放适配C:百分比布局D:rem布局，动态设置根元素大小	", out:"	参考答案：ABCD	"},
                    {title:"	Antd的导航菜单组件Menu，可以使用在如下哪些场景	", option:"	A:顶部菜单B:底部菜单C:右侧菜单D:左侧菜单	", out:"	参考答案：AD	"},
                    {title:"	以下哪些是HTML5新标签	", option:"	A:audioB:canvasC:spanD:section	", out:"	参考答案：ABD	"},
                    {title:"	redux数据更新正确的是	", option:"	A:UIdipacthactionB:actiondispatchreducerC:UI触发actionD:reducerupdatestore	", out:"	参考答案：BCD	"},
                    {title:"	H5性能优化可以从哪入手	", option:"	A:图片方面B:加载方面C:渲染方面D:CSS方面E:脚本方面	", out:"	参考答案：ABCDE	"},
                    {title:"	() => {} 是ES6的新语法	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	react组件销毁回调的方法是componentWillMount	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	react的keys的作用是用于追踪哪些列表中元素被修改、添加或者移除的辅助标识？	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	如果使用let，声明的变量仅在块级作用域内有效	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	componentDidUpdate() 组件更新后调用	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	以下属于HTML结构化标签的是	", option:"	A:headerB:divC:footerD:nav	", out:"	参考答案：ABCD	"},
                    {title:"	Antd中日期类组件包括以下哪些形式	", option:"	A:MonthPickerB:DatePickerC:PickerD:RangePicker	", out:"	参考答案：ABD	"},
                    {title:"	组件this.props.children的值会有哪几种可能？	", option:"	A:当前没有子节点，则为nullB:有多个子节点，数据类型为arrayC:当前没有子节点，则为undefinedD:有一个子节点，数据类型为object	", out:"	参考答案：BCD	"},
                    {title:"	html语义化是合适的标签标识适当的内容，可以起到搜索引擎优化，提高可访问性，与此同时还可提高代码的可读性。总而言之就是在正确的地方使用正确的标签	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	React组件中必须要有的方法是componentWillMount	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	React自定义组件首字母大小写都可以	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	antd的Popover气泡卡片和 Tooltip 的区别是，用户可以对浮层上的元素进行操作，因此它可以承载更复杂的内容，比如链接或按钮等	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	使用云凤蝶，如果想要从路由获取参数，最优的方式是什么？	", option:"	A:在页面加载时解析location.hrefB:后端提供参数接口C:右键页面设置动态路由D:在应用初始化时解析location.href	", out:"	参考答案：C	"},
                    {title:"	state跟props的描述正确的是？	", option:"	A:state和props改变后都会触发渲染B:state只存在组件的内部C:state和props都是可以改变的D:props在所有实例组件共享	", out:"	参考答案：ABD	"},
                    {title:"	antd的Modal组件有以下几种Method	", option:"	A:Modal.warning()B:Modal.info()C:Modal.success()D:Modal.error()	", out:"	参考答案：ABCD	"},
                    {title:"	使用云凤蝶，如果想根据条件渲染不同内容可以用哪些方式实现？	", option:"	A:高级属性里的条件渲染B:写代码修改DOM节点C:多状态面板组件D:写代码增删组件元素	", out:"	参考答案：AC	"},
                    {title:"	当你的项目中有显示头像的需求，那么可以使用Antd的Avatar组件	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	类似 Select 的选择控件，可选择的数据结构是一个树形结构时可以使用Antd的TreeSelect	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	dva中用户交互触发会改变数据的时候可以通过 dispatch 发起一个 action	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	constructor是组件的构造函数，会在创建实例时自动调用	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	云凤蝶中，下列哪个自定义组件装饰器描述不准确？	", option:"	A:属性和事件标注均可提供默认值B:@eventProperty用于标注对外暴露事件C:外部使用方传入的函数入参与@eventProperty标注函数的入参一致D:@property用于标注对外暴露属性	", out:"	参考答案：C	"},
                    {title:"	Calendar是antd的日历组件	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	React组件中必须要有的方法是render	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	在云凤蝶如果待做的应用没有独立的页面服务端，只有 TR 接口，需要选择哪种方案？	", option:"	A:BigFlyB:OneXC:反向代理D:云凤蝶托管服务	", out:"	参考答案：D	"},
                    {title:"	以下关于dva的描述正确的是	", option:"	A:reducer:Action处理器，处理同步动作，用来算出最新的StateB:namespace:当前Model的名称。整个应用的Model，由多个小的Model合成C:effects：Action处理器，处理异步动作D:state:该Model当前的状态。数据保存在这里，直接决定了视图层的输出	", out:"	参考答案：ABCD	"},
                    {title:"	Antd栅格系统所有列（Col）必须放在 Row 内	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	react的componentWillMount 方法会在render方法之后执行	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	当你想在页面上添加菜单时，可以使用antd的Menu组件	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	class MyTitle extends React.Component是 ES6 语法，表示自定义一个MyTitle类，该类继承了基类React.Component的所有属性和方法	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	关于base64，下面说法正确的是？	", option:"	A:方便传输数据，对数据进行简单的加密B:小图片base64后，可以减少http请求C:可以将二进制流转为字符流D:可减少内容体积E:是一种编码方式	", out:"	参考答案：ABCE	"},
                    {title:"	HTML 属性应该按照特定的顺序出现以保证易读性，而且一致的属性顺序可能提升 1.5% 的 gzip 压缩率	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	使用const声明的是变量，在后面出现的代码中可以修改该常量的值。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	以下哪个不是智能向导创建表格时可配置的？	", option:"	A:查询区B:全局操作C:排序D:背景色E:批量操作F:表格列G:分页器	", out:"	参考答案：D	"},
                    {title:"	智能向导不支持快速创建哪个表单类型？	", option:"	A:基础表单B:分组表单C:分步表单D:根据数据动态生成的表单项	", out:"	参考答案：D	"},
                    {title:"	自由布局下，下列哪个关于类型的设置描述是错误的？	", option:"	A:如果宽度设置固定，当父容器宽度发生变化时，宽度保持不变B:如果宽度设置适配内容，当内容发生变化时，宽度随内容变化C:如果父容器设置适配内容，子元素设置为自适应，子元素会随父元素变化D:如果宽度设置自适应，当父容器宽度发生变化时，宽度随父容器变化	", out:"	参考答案：C	"},
                    {title:"	导入的 NPM 不可以调整哪个配置？	", option:"	A:尺寸可选配置B:动效配置C:父子组件设置D:属性配置	", out:"	参考答案：B	"},
                    {title:"	下列哪个自定义组件装饰器描述不准确？	", option:"	A:外部使用方传入的函数入参与@eventProperty标注函数的入参一致B:@property用于标注对外暴露属性C:@eventProperty用于标注对外暴露事件D:属性和事件标注均可提供默认值	", out:"	参考答案：A	"},
                    {title:"	关于弹性布局，下列哪个描述是错误的？	", option:"	A:弹性布局下不可通过拖拽调整组件位置B:弹性布局支持横向和纵向排列C:弹性布局下，当父容器宽度或高度是适配内容时折行不生效D:弹性布局可以通过设置内外边距控制组件间距	", out:"	参考答案：A	"},
                    {title:"	如果想要从路由获取参数，最优的方式是什么？	", option:"	A:后端提供参数接口B:在页面加载时解析location.hrefC:右键页面设置动态路由D:在应用初始化时解析location.href	", out:"	参考答案：C	"},
                    {title:"	如果需要嵌入到已有的 procode （例如 umi ） 项目中，需要用哪种方案？	", option:"	A:BigFlyB:反向代理C:云凤蝶托管服务D:OneX	", out:"	参考答案：A	"},
                    {title:"	自由布局下，下列哪个不能达到预期？	", option:"	A:高度设置自适应，上下间距固定<imgsrc=\"https://intranetproxy.alipay.com/skylark/lark/0/2019/gif/648/1563783106931-af416369-6985-4452-8066-312e1d5c4326.gif\"alt=\"undefined\"style=\"float:none;height:auto;width:auto\"/>B:宽度设置自适应，左右间距设置自适应<imgsrc=\"https://intranetproxy.alipay.com/skylark/lark/0/2019/gif/648/1563783359400-bd3ff721-3893-4659-84e5-5db829e0570c.gif\"alt=\"undefined\"style=\"float:none;height:auto;width:auto\"/>C:宽度设置自适应，左右间距设置固定<imgsrc=\"https://intranetproxy.alipay.com/skylark/lark/0/2019/gif/648/1563782672830-7e8f9f8e-0605-4171-a79d-d22911e471e0.gif\"alt=\"undefined\"style=\"float:none;height:auto;width:auto\"/>D:两个组件设置宽度固定，左侧组件左间距固定，右间距自适应；右侧组件左间距自适应，右间距固定<imgsrc=\"https://intranetproxy.alipay.com/skylark/lark/0/2019/gif/648/1563793084910-2491ef74-3fa1-42d9-87dc-5d75acaa7cee.gif\"alt=\"undefined\"style=\"float:none;height:auto;width:auto\"/>	", out:"	参考答案：B	"},
                    {title:"	什么情况下反向代理后，访问页面会显示 Not Found 或 404？	", option:"	A:以上都是B:后端配置错误C:页面路由与后端不匹配D:忘记部署	", out:"	参考答案：A	"},
                    {title:"	如果待做的应用没有独立的页面服务端，只有 TR 接口，需要选择哪种方案？	", option:"	A:BigFlyB:OneXC:反向代理D:云凤蝶托管服务	", out:"	参考答案：D	"},
                    {title:"	云凤蝶支持对接下列哪些技术方案？	", option:"	A:SOFAB:ChairC:TRD:OneX	", out:"	参考答案：ABCD	"},
                    {title:"	以下哪种接口可以使用智能向导表格？	", option:"	A:接口返回的格式中带有对象数组B:接口返回的格式中带有对象C:接口返回的格式中最外层带有对象数组D:接口返回的格式中带有字符串	", out:"	参考答案：AC	"},
                    {title:"	如果有多个只读字段展示的例如详情页的需求，可以使用哪些方式实现？	", option:"	A:通过代码添加组件元素B:通过代码修改DOM节点C:使用描述列表组件D:使用多个文本组件手动排版	", out:"	参考答案：CD	"},
                    {title:"	云凤蝶支持制作哪些资产？	", option:"	A:应用模板B:导航栏C:组件D:区块模板	", out:"	参考答案：BCD	"},
                    {title:"	如果页面中有一部分组件、区域想在其他应用中使用有哪些方式？	", option:"	A:选中页面中组件用快捷键复制粘贴B:对页面右键复制到，然后选择目标应用C:创建一个资产包将组件复制到资产包，并在其他应用中引用资产包D:目标应用添加引用当前应用	", out:"	参考答案：ABC	"},
                    {title:"	如果想根据数组数据渲染一个列表可以用哪些方式实现？	", option:"	A:对想要重复的元素开启高级属性中的重复B:用代码控制动态添加组件元素C:直接在画布中复制粘贴D:使用列表组件，配置数据源	", out:"	参考答案：AD	"},
                    {title:"	如果想根据条件渲染不同内容可以用哪些方式实现？	", option:"	A:写代码修改DOM节点B:高级属性里的条件渲染C:写代码增删组件元素D:多状态面板组件	", out:"	参考答案：BD	"},
                    {title:"	云凤蝶的产品特点有哪些？	", option:"	A:精细化调整样式、动效，搭建个性化应用B:多种数据接口，语义化数据消费C:可视化搭建页面，内置权威资产D:从数据到应用，智能向导10倍提效	", out:"	参考答案：BCD	"},
                    {title:"	云凤蝶是蚂蚁的企业级应用设计研发平台，下列哪些不是云凤蝶的适用场景？	", option:"	A:基于业务UI组件库创建的应用B:交互复杂的CloudIDEC:大量表单表格的CRUD系统D:数据大盘、自定义的数据统计E:LandingPage引流、落地页F:外观独特的toC应用G:应用仪表盘、后台管理系统	", out:"	参考答案：BF	"},
                    {title:"	以下哪个写法是对的？	", option:"	A:<Buttononclick={onSubmit}>提交</Button>B:<Buttononclick={onsubmit}>提交</Button>C:<ButtononClick={onsubmit}>提交</Button>D:<ButtononClick={onSubmit}>提交</Button>	", out:"	参考答案：D	"},
                    {title:"	antd的Message组件提供了哪些静态方法	", option:"	A:message.error(content，duration，onClose)B:message.info(content，duration，onClose)C:message.warning(content，duration，onClose)D:message.success(content，duration，onClose)	", out:"	参考答案：ABCD	"},
                    {title:"	下面对react生命周期简述正确的是	", option:"	A:除了首次render之后调用componentDidMount，其它render结束之后都是调用componentDidUpdate。B:componentDidMount在组件挂载之后调用一次。这个时候，子主键也都挂载好了，可以在这里使用refs。，C:shouldComponentUpdate返回true或者调用forceUpdate之后，componentWillUpdate会被调用。D:beforeMount在挂载开始之前被调用：相关的render函数首次被调用。	", out:"	参考答案：ABC	"},
                    {title:"	antd的步骤条组件Steps中每个节点的图标可以更换	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	dva 是体验技术部开发的 React 应用框架，将上面三个 React 工具库包装在一起，简化了 API，让开发 React 应用更加方便和快捷	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	ES6编码规约规定使用 let 或者 const 代替 var	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	let不允许在相同作用域内，重复声明同一个变量	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	eslint代码检查工具可以帮你检查js代码语法和格式	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	如果希望在react组件销毁时清理一些东西，例如回收定时器和取消代理时，要用到componentWillUnMount方法	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	使用let声明的变量，其作用域为该语句所在的代码块内，不存在变量提升	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	antd的Collapse折叠组件可以对复杂区域进行分组和隐藏，保持页面的整洁	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	dva中可以通过 dva-loading 处理 loading 状态	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	render()函数中返回的所有元素没必要包裹在一个根元素里面	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	antd的级联组件Cascader在何时使用	", option:"	A:比起Select组件，可以在同一个浮层中完成选择，有较好的体验B:一组选择数据时C:从一个较大的数据集合中进行选择时，用多级分类进行分隔，方便选择D:需要从一组相关联的数据集合进行选择，例如省市区，公司层级，事物分类等	", out:"	参考答案：ACD	"},
                    {title:"	以下符合React编码规约的是	", option:"	A:constReservationItem=<ReservationCard/>;B:importreservationCardfrom'./ReservationCard';C:importReservationCardfrom'./ReservationCard';D:constreservationItem=<ReservationCard/>;	", out:"	参考答案：CD	"},
                    {title:"	Antd的Dropdown下拉菜单，当页面上的操作命令过多时，用此组件可以收纳操作元素	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	antd的Badge徽标数一般出现在通知图标或头像的右上角，用于显示需要处理的消息条数，通过醒目视觉形式吸引用户处理	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	React组件内部通过this.props获取参数	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	dva是双向数据流？	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	antd的评分组件Rate的星星视图可以替换为其他字符	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	以下哪一项sla评分会出现扣款情况？	", option:"	A:4B:4.5C:3.5D:2.5	", out:"	参考答案：D	"},
                    {title:"	SLA一般是多长时间评分一次?	", option:"	A:每周B:每月C:每季度D:每年	", out:"	参考答案：C	"},
                    {title:"	根据蚂蚁技术外包胜任力模型，以下哪个是高级同学的基本特征？	", option:"	A:独当一面、攻坚克难B:独当一点，高质完成C:基础扎实、协作开发D:独当一线、指导团队	", out:"	参考答案：D	"},
                    {title:"	SLA的评分流程是	", option:"	A:外包团队自评，业务方终评B:外包团队与业务方同时评价C:直接由外包团队做评分D:直接由业务方做评分	", out:"	参考答案：A	"},
                    {title:"	ITO系统中需求完成的有效工时如何认定？	", option:"	A:需求预估工时即可认定为有效工时B:业务方直接给出有效工时数据C:供应商提交的实际工时即可认定D:供应商提交实际工时，业务方认定有效工时	", out:"	参考答案：D	"},
                    {title:"	根据技术外包安全行为规范，以下哪些行为禁止	", option:"	A:将工作资料上传至云盘或githubB:拥有线上生产环境权限，线上查询日志权限、生产环境操作权限C:通过微信、QQ传输工作资料D:将工作资料下载至私人手机	", out:"	参考答案：ABCD	"},
                    {title:"	蚂蚁SLA的结构包含哪几部分	", option:"	A:合作满意度B:人员管理C:研发效能D:需求交付	", out:"	参考答案：ABCD	"},
                    {title:"	蚂蚁技术外包胜任力模型中，胜任力维度有哪些	", option:"	A:沟通组织能力B:岗位能力C:执行能力D:业务理解能力	", out:"	参考答案：ABD	"},
                    {title:"	下列符合蚂蚁金服-技术外包信息安全行为规范—终端设备安全的有	", option:"	A:接入蚂蚁金服办公网络的工作电脑必须安装DLP防数据泄露软件产品B:禁止自行更改网络配置C:接入蚂蚁金服办公网络环境，需安装配置阿里郎，并必须保持阿里郎处于启动状态D:禁止将私人计算机或笔记本接入工作网络	", out:"	参考答案：ABCD	"},
                    {title:"	信息安全行为规范，以下哪些行为是正确的	", option:"	A:工作电脑或工作平台的账号和密码不能随意外泄（例：抄写于便签，贴在电脑上），离开电脑1分钟以上需锁屏。B:工作时间禁止进行与工作无关的网上聊天、娱乐、炒股、或者收发非工作邮件。C:含业务信息的纸质文件必须用碎纸机销毁；不能手撕或直接丢弃。D:公司配备员工的电脑坏了，员工自己可以拿去任何电脑修理店修理	", out:"	参考答案：ABC	"},
                    {title:"	下列属于技术外包信息安全行为规范的操作风险规范的有	", option:"	A:外包工作场地中配备的所有办公设备必须通过有线网络接入蚂蚁金服网络环境B:不得以任何形式（包括但不限于WIFI共享、自建AP等）将蚂蚁金服的办公网络暴露或共享到无线环境中C:工作中使用互联网沟通工具，仅限于使用蚂蚁金服后缀邮箱、阿里工作旺旺、钉钉等蚂蚁金服明确允许的通讯类产品D:禁止在非蚂蚁金服网络环境下通过远程访问（如VPN，RDP等）的方式，访问蚂蚁金服网络环境	", out:"	参考答案：ABCD	"},
                    {title:"	以下对于权限风险描述正确的是	", option:"	A:工作邮箱可以在他人电脑上登录查收邮件B:不得将拥有的权限用于非工作目的，例如利用权限查询亲友或他人信息、查看超出实际工作需要的蚂蚁员工信息、日志信息等等。C:不得使用本地管理员权限来卸载公司要求安装的软件或更改操作系统的安全策略。D:不允许转借域账号给他人使用	", out:"	参考答案：BCD	"},
                    {title:"	蚂蚁技术外包胜任力模型的主要应用包括	", option:"	A:绩效参考B:招聘定级参考C:调级的必要条件D:培训方向参考	", out:"	参考答案：ABCD	"},
                    {title:"	ITO系统中可由外包团队进行操作的功能包括	", option:"	A:需求验收提交B:需求分配C:需求信息查看D:需求建立	", out:"	参考答案：ABC	"},
                    {title:"	SLA中开发类线下质量包含以下哪几项	", option:"	A:线下缺陷密度B:代码与设计质量C:工作规范性D:自测可发现缺陷密度	", out:"	参考答案：ABD	"},
                    {title:"	以下常见考核指标解释正确的是	", option:"	A:线上故障数：考核引发线上故障的数量B:代码与设计质量：考察代码与设计的规范性、可维护性、扩展性、完整性C:线下缺陷密度=线下缺陷数*1000/发布上线代码总行数D:合作满意度：考核服务中外包人员的工作态度，沟通主动性，团队合作等能力	", out:"	参考答案：ABCD	"},
                    {title:"	工作电脑必须安装正版操作系统和文档处理软件，并确保安全补丁及时更新。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	根据蚂蚁技术外包胜任力模型对业务理解能力的要求，初级同学要了解业务点、中级同学要了解业务线、高级同学要了解业务线细节、资深和专家同学要了解整体业务发展方向。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	蚂蚁技术外包胜任力模型展现了对外包同学的能力要求框架，其中的一些能力要求可以根据实际情况进行调整、细化。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	根据蚂蚁技术外包胜任力模型，要求资深、专家级同学需要精通某领域技能。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	请假管理：如果请假，需要提前或当天在ITO上填写请假记录	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	需求评分0-1分表示需求交付完全没有达到要求/效率低，有严重质量问题	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	外包不得拥有线上生产环境权限，线上查询日志权限。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	合同有效期间内，蚂蚁金服在职的外包员工只能为蚂蚁金服提供服务，不得同时服务于其他公司。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	SLA中自评4分、5分的评分项需要有案例支持并注明。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	整体SLA评分要达到多少分才算满足期望？	", option:"	A:5分B:3.5分C:3分D:4分	", out:"	参考答案：B	"},
                    {title:"	安全行为B类违规，会进行哪一项处罚	", option:"	A:进行1000元人民币/次的罚款B:按照单个项目金额的30%（服务按当月结算金额的100%）C:以上都是错误的D:按照单个项目金额的10%（服务按当月结算金额的30%）进行处罚	", out:"	参考答案：D	"},
                    {title:"	ito系统（蚂蚁技术外包的工作管理平台）可以进行的操作和注意事项描述正确的是	", option:"	A:SLA打分，一般每三个月进行一次SLA评分，低于3.5分会有扣费。B:请假需在ito系统进行录入，需提前或当天在ITO上填写请假记录C:加班无法录入，需提前发送加班邮件并得到业务方确认后，才能在填写实际工时加上加班时间。D:需求管理，完整的流程是新建需求、分配需求、提交验收、需求评价	", out:"	参考答案：ABCD	"},
                    {title:"	以下哪些是蚂蚁外包服务SLA中常用的考核指标	", option:"	A:代码与设计质量、交付进度、独立服务能力B:系统平均分、自测可发现缺陷密度、SIT缺陷漏检率C:线上故障数、代码缺陷密度D:到岗率、流动率	", out:"	参考答案：ACD	"},
                    {title:"	技术外包信息安全入职考试须知描述正确的是	", option:"	A:未在规定时间内通过安全考试，属于C类违规B:考试90分通过C:每人有20次考试机会D:需在入职两周内完成	", out:"	参考答案：ABCD	"},
                    {title:"	关于终端设备，违反以下哪几条将视为A类违规	", option:"	A:技术外包必须统一使用蚂蚁金服提供的办公设备（仅限台式电脑和公共测试手机），禁止员工自带私人或供应商计算机或笔记本（包括但不限于MAC等）进入蚂蚁金服工作区域办公。B:UED等离场办公外包人员，工作电脑应当接入外包供应商域控，供应商应统一设置口令安全策略、用户权限；并及时更新补丁、安装防病毒软件等；供应商及外包人员应保护终端安全，避免因终端安全、网络安全保护疏忽导致数据泄露，或将病毒、恶意代码等随工作交流传入蚂蚁金服网络等不良后果。C:不得以任何形式将蚂蚁金服资产或移动设备带出工作区域（包括但不限于打印件带出、拷贝到U盘或移动硬盘、上传到云盘、github、邮件外发、FTP上传等方式）。D:使用蚂蚁金服提供的工作电脑时，不要点击来历不明的邮件或链接，不要访问与工作无关的站点。	", out:"	参考答案：AB	"},
                    {title:"	根据蚂蚁技术外包胜任力模型，高级同学只要技术能力强就行了，有没有能力培养新人无所谓。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	需求评分3分表示需求交付基本符合要求	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	蚂蚁技术外包胜任力模型主要作用是明确蚂蚁对技术外包同学多维度能力要求，同时向外包同学展现在蚂蚁的发展路径。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	需求评分5分表示需求交付完成超出预期，非常满意	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	需求评分2分表示需求交付不符合要求/功能未完成满足/质量有问题	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	服务需求评价结果，需求方系统平均分为0分，表明需求方对该团队非常满意	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	SLA需要根据服务的具体情况设定，可以设定与模板不一致的指标项。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	外包同学在调级申请时需要参照胜任力模型充分阐述是否达到下一层级的要求。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	工作平台的账号和密码可以告诉同事	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	需求评分4分表示需求交付符合要求，且在过程/效率/质量方面有一定亮点	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	非生产账号密码可以直接放在语雀平台，不需要进行权限设置或脱敏处理。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	根据蚂蚁技术外包胜任力模型，以下哪个是中级同学的基本特征	", option:"	A:独立高效完成简单工作B:在指导下完成简单工作C:精通某领域技能D:带团队解决技术疑难	", out:"	参考答案：A	"},
                    {title:"	sla自评页面，【测试类】线下质量（SIT缺陷漏检率），评分是2分，则那种情况符合2分的场景	", option:"	A:SIT和预发缺陷总数为0，并能采取有效措施避免SIT缺陷的发生B:SIT和预发缺陷率（所有类型总和）介于0-10%C:因漏测导致主功能不完整或发布延期D:大量测试原因导致的SIT和预发缺陷，大于20%	", out:"	参考答案：D	"},
                    {title:"	禁止外包员工具备线上生产环境的操作权限	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	日常工作中用到的软件，只要是免费的，都可以下载安装	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	外包可以接触到真实的生产数据，未脱敏的测试环境与开发环境。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	在一个服务考核周期内，如果有业务方的正式邮件投诉，第一次投诉给予警告，第二次投诉执行扣罚。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	某同学休假在家，但手头有紧急任务处理，可以用个人电脑登陆阿里郎接入蚂蚁金服网络并登陆内部系统处理。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	需求方在SLA评分中，给予系统平均分为5分，则业务方的满意程度是那一项？	", option:"	A:低于期望B:满足期望C:超出期望D:以上都不是	", out:"	参考答案：C	"},
                    {title:"	以下关于技术外包信息安全行为规范描述正确的是：	", option:"	A:外包供应商必须与为蚂蚁金服服务的外包员工签订保密协议。B:禁止外包员工个人移动设备接入蚂蚁金服网络环境。特殊情况，必须由蚂蚁金服业务主管协助申请，经蚂蚁金服信息安全相关团队及IT部门审批与备案后方可使用。C:工作时间可以进行与工作无关的网上聊天、娱乐、炒股、或者收发非工作邮件。D:新外包员工要求在入职2周内完成信息安全培训及商业行为准则认证，并通过相应的考试。E:合同有效期间内，蚂蚁金服在职的外包员工只能为蚂蚁金服提供服务，不得同时服务于其他公司。	", out:"	参考答案：ABDE	"},
                    {title:"	以下哪些行为属于安全行为A类违规	", option:"	A:外包人员在蚂蚁金服员工工作区域办公B:出售、利用、复制、传播或擅自修改项目信息C:合同有效期间内同时服务于其他公司D:将蚂蚁金服工作旺旺、钉钉、域账号、工作邮箱、工作电脑等信息资产借给他人使用	", out:"	参考答案：ABCD	"},
                    {title:"	入职两周内需要完成的工作包括	", option:"	A:加入外包钉钉考勤专用组B:学习安全行为规范并完成考试C:检查电脑是否按要求按照阿里郎、云壳、DLP、EDR、杀毒软件D:完成入职岗位考试	", out:"	参考答案：ABCD	"},
                    {title:"	业务方在ITO系统中提交的需求评价分数可以作为服务质量的参考，但不会作为结算依据	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	外包人员关于权限风险，特殊情况，必须由蚂蚁金服业务主管协助申请，蚂蚁金服信息安全相关团队审批与备案后方可使用。过程审批件请抄送到给蚂蚁技术外包管理团队。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	sla自评中，子评估项：工作过程规范，产出物符合要求，评分为4分，则需要案例支持	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	业务方要求我去蚂蚁自有员工工作场地办公，既然是业务方要求，我就可以去。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	外包团队提交的工时可以直接作为结算依据。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	sla评分分值大于等于多少会出现项目奖金？	", option:"	A:4B:3C:4.1D:3.5	", out:"	参考答案：C	"},
                    {title:"	AONE平台中测试（验证者）发现了问题。提交一个缺陷默认状态为？	", option:"	A:FixedB:CloseC:OpenD:New	", out:"	参考答案：D	"},
                    {title:"	什么命令用来查看版本信息	", option:"	A:gitlogB:gitstatusC:gitdiffD:gitbranch	", out:"	参考答案：A	"},
                    {title:"	为什么要写系分？	", option:"	A:识别风险B:制定研发计划C:体现设计思路D:便于分享	", out:"	参考答案：C	"},
                    {title:"	系分文档中用例图是什么？	", option:"	A:描述各个系统之间的关系B:所能观察到的系统功能的模型图C:绘制前端DEMOD:用来描述某个功能的走向	", out:"	参考答案：B	"},
                    {title:"	关于linke的描述，以下错误的是	", option:"	A:面向开发和测试人员的智能研发平台B:可以支持不同研发环境下自动编译部署C:提供各类场景化分析、定制化质量和风险控制能力，让研发更加简单、高效、可靠D:可以作为产品设计工具使用	", out:"	参考答案：D	"},
                    {title:"	下列选项不属于细化流程的是	", option:"	A:编写接口测试脚本B:细化补充流程C:用例价值分析D:业务边界分析	", out:"	参考答案：A	"},
                    {title:"	质量红线规定典型故障不能再犯几次？	", option:"	A:4次B:1次C:3次D:2次	", out:"	参考答案：B	"},
                    {title:"	质量红线是什么?	", option:"	A:一系列项目过程中必须达到的标准统称。B:项目的需求C:开发代码的备注D:产品经理的要求	", out:"	参考答案：A	"},
                    {title:"	切换已存在的分支是用什么命令	", option:"	A:gitcheckoutdevB:gitcheckout--devC:gitcheckout–bdevD:gitbranchdev	", out:"	参考答案：A	"},
                    {title:"	下列说法正确的是	", option:"	A:代码变更的基本信息中，有操作关联发布的地方，会被显示出来，用于关联。B:SIT的缺陷必须要有关联CR任务，必须填写CR人员。C:CR任务必须是已处理情况下，测试人员可以关闭缺陷任务。D:不是每个代码变更都必须要关联发布。	", out:"	参考答案：B	"},
                    {title:"	Stable环境连接的是哪个数据库？	", option:"	A:TEST（SIT）B:代码源C:生产D:DEV	", out:"	参考答案：D	"},
                    {title:"	把文件提交到仓库的git命令是？	", option:"	A:gitcommitB:gitinitC:gitdiffD:gitadd	", out:"	参考答案：A	"},
                    {title:"	git能在哪些系统上安装？	", option:"	A:MacOSB:WindowsC:以上系统都可安装D:Linux	", out:"	参考答案：C	"},
                    {title:"	如果你正在一个分支上开发，还没完成，不能提交到主干，但突然测试提了一个bug给你，而且这个bug必须先修复，你对你当前开发的分支将进行什么操作	", option:"	A:gitrebasemasterB:gitstashC:gitstashpopD:gitmergemaster	", out:"	参考答案：B	"},
                    {title:"	服务器部署问题排查说法不正确的是	", option:"	A:非启动引起的问题需要查看编译日志，检查部署CE、JDK版本是否正确B:sofa-startup.log可以查看应用启动的相关问题C:需要使用SSH软件登陆服务器，查看服务器日志D:启动日志一定在/home/admin/logs/应用名/sofa/下	", out:"	参考答案：D	"},
                    {title:"	缺陷责任人填写原则有	", option:"	A:编码相关的填写造成缺陷的代码的作者B:需求相关的填写变更人或者原需求作者C:第三方原因填写第三方owner，例如下游系统owner，数据原始作者等D:没有对应人的，如服务器异常、网络抖动、历史遗留但对应开发已离职无法选取等，这种【定位不到责任人但确定不是自己的原因的】，则填自己的业务方技术主管。	", out:"	参考答案：ABCD	"},
                    {title:"	不做业务分析有什么风险与危害？	", option:"	A:用户体验差B:无法识别需求风险与缺陷C:沟通效率低下D:需求范围容易失控	", out:"	参考答案：ABCD	"},
                    {title:"	关于红线质量故障说法正确的是	", option:"	A:故障分析深入以及后续action落实到位，action要求可操作并在截止日期前完成落地B:典型故障不能再犯第二次C:若有巡检报警，需第一时间给出解释并排查原因D:红线故障是开发人员重点关注的点，测试人员可以不予关注	", out:"	参考答案：ABC	"},
                    {title:"	质量红线流程规范中严禁事项有	", option:"	A:严禁发布后不执行线上验证B:严禁代码未经测试或未经开发自测发布上线C:严禁线上配置未经验证全网推送D:严禁发布后没有对应的回滚方案	", out:"	参考答案：ABCD	"},
                    {title:"	code review时开发主要review内容有哪些	", option:"	A:变更代码B:业务代码逻辑C:用例覆盖情况D:自动化脚本	", out:"	参考答案：AB	"},
                    {title:"	测试过程管理中如何控制测试版本	", option:"	A:指定合理的版本发布计划B:做好测试过程中风险的识别和反馈C:强化测试准入条件D:做好版本控制的文档管理	", out:"	参考答案：ABCD	"},
                    {title:"	业务需求有变化，以下说法正确的是	", option:"	A:新需求可以满足，但是BUG原因责任人实事求是不背锅B:开发为了开启主干的提交权限要求提交缺陷，这个锅不背，让开发自己去提缺陷吧C:最近缺陷有点多，和测试哥哥搞好关系，提个REOPEND:大家都是同事，修复缺陷的时候不好意思填其他人为责任人，算了，自己牺牲一下吧	", out:"	参考答案：AB	"},
                    {title:"	客户反馈有5000条数据有错别字，我直接DB订正掉就好了，也不用告诉其他人	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	配置git账号只需要git config --global user.name即可	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	项目经理主要负责项目协调，开发测试进度需要开发与测试人员自己把握。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	git status命令可以让我们时刻掌握仓库当前的状态。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	Aone系统中，我们最常用到的流程就是代码变更流程。这个管理了我们日常的发布、紧急发布的过程。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	所有线上操作必须提交变更单进行备案	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	如果将其他分支的修改合并到当前分支的时候想要要干净的、线性的提交树，使用merge操作会好一点？	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	在新的研发流程中，只要通过预发验证，便可以发布上线	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	代码变更流程不包含哪些阶段	", option:"	A:待合并B:未拉流C:已合并D:已拉流	", out:"	参考答案：B	"},
                    {title:"	为什么要做业务分析？	", option:"	A:阻止其他人变更需求B:快速将项目上线C:正确理解业务的核心诉求、价值D:让自己不加班	", out:"	参考答案：C	"},
                    {title:"	AONE平台中如何查看我参与的所有项目？	", option:"	A:项目->我的工作项B:研发->应用C:项目->项目列表D:通用->质量	", out:"	参考答案：C	"},
                    {title:"	以下项目经理的简称是哪个	", option:"	A:PDB:TLC:以上均错误D:PM	", out:"	参考答案：D	"},
                    {title:"	出现质量红线如何处理？	", option:"	A:质量红线问题必须修复，不修复不能发布B:能解决就解决，不能解决就算了，不能影响项目进度C:直接无视D:放到下个迭代处理	", out:"	参考答案：A	"},
                    {title:"	《PRD文档》是在哪个阶段完成的文档？	", option:"	A:开发阶段B:测试阶段C:需求阶段D:发布阶段	", out:"	参考答案：C	"},
                    {title:"	《系分文档》是以下角色中谁完成的工作？	", option:"	A:项目经理B:测试人员C:开发工程师D:架构师	", out:"	参考答案：C	"},
                    {title:"	linke提交配置变更步骤	", option:"	A:进入迭代详情，点击“配置变更”，点击需要变更的配置种类，点击保存按钮B:进入迭代详情，点击“标准迭代”，点击需要变更的配置种类，填写变更表单，点击保存按钮C:进入迭代详情，点击“申请服务器”，点击需要变更的配置种类，填写变更表单，点击保存按钮D:进入迭代详情，点击“配置变更”，点击需要变更的配置种类，填写变更表单，点击保存按钮	", out:"	参考答案：D	"},
                    {title:"	需求阶段重要的产出物包括：	", option:"	A:标准项目安全分析报告B:产品需求文档C:白板设计D:测试分析文档	", out:"	参考答案：ABC	"},
                    {title:"	下列哪些原因会导致需求和设计实现不一致	", option:"	A:需求缺失B:设计缺失C:设计偏差或需求不合理	", out:"	参考答案：ABC	"},
                    {title:"	出现哪些问题算触犯了质量红线？	", option:"	A:再次出现典型的线上故障B:有later状态的bugC:PDM扫描有阻断与严重问题D:项目延期发布	", out:"	参考答案：AC	"},
                    {title:"	所有线上操作必须提交变更单进行备案。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	linke 提交代码-MR模式步骤：1.进入迭代详情。2.在操作菜单区， 3.点击 “提交MR”，4，等待 pipeline 展示并执行，5查看 pipeline 执行结果	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	切换分支命令是git checkout	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	linke新建迭代三要素： 迭代名称、涉及的应用清单、关联工作项清单	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	预发环境，上线前最后一步测试，由测试以及各方进行预发测试以及功能验收，与Test环境的区别在于预发环境所连的数据库为真实数据库。用真实的数据来进行功能验收，基本与线上环境一致	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	项目代码合并后，测试进入SIT阶段，测试使用stable环境，一般一个应用对应多个stable环境且固定	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	需求评审通过后，开发同学和测试同学下一步需要做什么：	", option:"	A:开发同学：代码编写；测试同学：用例编写B:开发同学：测分设计；测试同学：系分设计C:开发同学：系分设计；测试同学：测分设计D:开发同学：代码编写；测试同学：功能测试	", out:"	参考答案：C	"},
                    {title:"	git命令使用，哪个命令是切换到master分支	", option:"	A:gitcheckoutmasterB:gitmergeC:gitbranch-dD:gitbranch	", out:"	参考答案：A	"},
                    {title:"	git add命令是把文件修改添加到什么地方	", option:"	A:暂存区B:远程仓库C:当前分支D:工作区	", out:"	参考答案：A	"},
                    {title:"	在ANONE中新建代码变更前，首先需要做些什么	", option:"	A:新建缺陷B:新建项目C:新建配置项变更D:新建需求	", out:"	参考答案：B	"},
                    {title:"	数据设计是以什么为输入的?	", option:"	A:其它相关项目B:开发者随意拼装C:用例图D:业务分析（对象领域模型）	", out:"	参考答案：D	"},
                    {title:"	在ANONE中申请权限以下说法正确的是	", option:"	A:申请理由可以随便写B:填写申请的应用可以填写多个C:读写权限和只读权限都要申请D:申请权限时间越长越好	", out:"	参考答案：B	"},
                    {title:"	GIT如何创建分支	", option:"	A:gitpushxxxB:gitbranchxxxC:gitcheckoutxxxD:gitclone	", out:"	参考答案：B	"},
                    {title:"	关于缺陷状态，以下说法错误的是	", option:"	A:当开发在多个环境下无法对该缺陷进行复现。则选择worksformeB:开发判断缺陷为外部引入导致的，并且不需要我们修复，则选择ExternalC:测试确定该有效的缺陷已经完成修复，选择close关闭缺陷D:当开发发现这个缺陷是无效的，和测试沟通，将缺陷Invalid，最后测试把该缺陷close	", out:"	参考答案：D	"},
                    {title:"	项目整个流程中质量红线最多可容忍出现几个?	", option:"	A:0B:2C:4D:1	", out:"	参考答案：A	"},
                    {title:"	新建配置项变更流程正确的是？	", option:"	A:SIT通过-合并通过-开发编辑-开发提交B:开发编辑-开发提交-SIT通过-合并通过C:开发编辑-开发提交-合并通过-SIT通过D:开发提交-开发编辑-SIT通过-合并通过	", out:"	参考答案：C	"},
                    {title:"	业务分析中，细化补充流程主要包括	", option:"	A:业务主流程、分支流程B:正向流程、反向流程C:异常流程D:交互体验分析、业务量评估、本厂特有的影响分析	", out:"	参考答案：ABCD	"},
                    {title:"	Aone平台的系统整体结构有哪几部分？	", option:"	A:项目B:研发C:通用D:我的（工作台）	", out:"	参考答案：ABCD	"},
                    {title:"	AONE平台中如何查看我的代办工作项？	", option:"	A:以上都均错误B:工作台->待我处理C:工作台->我的指派D:项目->我的工作项->指派给我的	", out:"	参考答案：BD	"},
                    {title:"	关于SIT缺陷类型选择，以下说法正确的是	", option:"	A:测试代码脚本的修改或单元测试的修改等原因引发的缺陷可选择其他B:因业务需要，测试从SIT及以后的阶段介入测试属于已知问题或风险C:预发/正式环境发现的问题一律属于线上问题D:测试有相关用例，但在DEV环境没有覆盖到该缺陷属于测试分析遗漏	", out:"	参考答案：ABC	"},
                    {title:"	针对技术改造类需求需要思考哪些	", option:"	A:是否考虑到业务发展状况B:改造价值C:技术瓶颈D:设计是否解决问题	", out:"	参考答案：ABCD	"},
                    {title:"	以下对新建缺陷描述错误的是（）	", option:"	A:责任人填写引起该缺陷的代码负责人，也可以填解决者。B:缺陷关联的CR任务未完成，测试也可以关闭缺陷。C:新建sit缺陷时可以不填CR人员，状态改为fix时才需要填写CR人员D:缺陷类型、缺陷原因必须由测试负责填写	", out:"	参考答案：BD	"},
                    {title:"	PD（Product ）的职责是了解用户和市场需求，提交需求给开发部门，产生PRD文档。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	Aone系统中，是否具备创建缺陷的功能？	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	蚂蚁域内除紧急发布外采用分支开发，主干发布策略。紧急发布采用分支开发，分支发布方式。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	PMD是一个开源代码分析器，PMD可以在不运行Java程序的情况下分析获知代码错误并报告错误。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	一般情况日常环境及stable环境连dev库，test环境连test库，预发环境连线上库	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	以下产品经理的简称是哪个	", option:"	A:PMB:PDC:TLD:以上均错误	", out:"	参考答案：B	"},
                    {title:"	申请开发环境后，启动日志存放的路径为？（金融云除外）	", option:"	A:/home/admin/logs/应用名/sofa/B:/home/admin/logs/sofa/应用名C:/home/admin/logs/应用名D:/home/admin/应用名/logs/sofa/	", out:"	参考答案：A	"},
                    {title:"	以下说法正确的是	", option:"	A:代码CR后测试/PM/PD认为可以优化的点导致的缺陷不是开发的责任B:由于灰度回滚导致的代码不一致引发的缺陷不是开发的责任C:sofa的健康检查在特定环境中出现异常导致的缺陷是开发的责任D:测试根据需求变更、代码接口变更等修改测试用例而导致的缺陷是开发的责任	", out:"	参考答案：B	"},
                    {title:"	以下哪个不是质量红线故障要求？	", option:"	A:故障数超过了5个B:故障分析深入以及后续action落实到位，action要求可操作并在截止日期前完成落地C:若有巡检报警，需第一时间给出解释并排查原因D:典型故障不能再犯第二次	", out:"	参考答案：A	"},
                    {title:"	测试人员在aone上提的缺陷需要填写什么？	", option:"	A:解决者B:优先级C:严重程度D:标题	", out:"	参考答案：ABCD	"},
                    {title:"	aone上包含了哪些项目信息？	", option:"	A:开发B:质量C:需求D:缺陷	", out:"	参考答案：ABCD	"},
                    {title:"	代码合并主干前，需要注意哪些：	", option:"	A:发起会审前，需要把该迭代关联发布窗口B:检查功能测试阶段的BUG是否全部修复完毕C:提醒开发同学是否已完成技术风险评估文档和发布计划文档D:提醒开发同学是否有配置项变更	", out:"	参考答案：ABCD	"},
                    {title:"	AONE中sit阶段修复bug代码不需要CR人员review，自己review就行。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	git add是把本地文件提交到仓库吗？	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	linke新建迭代步骤：1.平台右上角点击 + .2点击 “标准迭代”3.填写申请表单 4.点击 “新建”	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	申请的开发机部署出现了异常该怎么做	", option:"	A:重新申请一台新的开发机B:用服务器小工具升级开发机C:登陆开发机查看日志定位问题D:放着不管	", out:"	参考答案：C	"},
                    {title:"	如果你本地已经建了一个仓库，怎么关联远程仓库	", option:"	A:gitpush–uoriginmasterB:gitinitC:gitclonegit@gitlab.alipay-inc.com:zhangsan/learngit.gitD:gitremoteaddorigingit@gitlab.alipay-inc.com:zhangsan/learngit.git	", out:"	参考答案：D	"},
                    {title:"	以下哪个是TEST环境	", option:"	A:SIT环境B:沙箱环境C:DEV环境D:STABLE环境	", out:"	参考答案：A	"},
                    {title:"	关于linke发布阶段后需要提交到发布平台发布， 提交发布的前提提交为	", option:"	A:该迭代的所有研发活动都已经到了发布阶段，如果迭代关联到了日常发布，那么整个日常发布包含的所有研发活动都已经到了发布阶段。B:该迭代的所有研发活动都已经到了测试阶段，如果迭代关联到了日常发布，那么整个日常发布包含的所有研发活动都已经到了测试阶段。C:该迭代的所有研发活动都已经到了测试阶段，如果迭代关联到了日常发布，那么整个日常发布包含的所有研发活动都已经到了测试阶段。D:该迭代的所有研发活动都已经到了发测试段，如果迭代关联到了日常发布，那么整个日常发布包含的所有研发活动都已经到了测试阶段。	", out:"	参考答案：A	"},
                    {title:"	以下SIT问题，属于测试责任的有	", option:"	A:测试有相关用例，但在DEV环境没有覆盖到该缺陷B:开发则系分中没有体现，测试也没有在测分中体现，SIT发现的缺陷C:测试代码脚本的修改或单元测试的修改等原因引发的缺陷D:dev阶段已测出缺陷，但当前环境不允许只能在SIT阶修复	", out:"	参考答案：AB	"},
                    {title:"	以下哪些状态的缺陷是无效的？	", option:"	A:InvalidB:ByDesignC:WorksformeD:Duplicate	", out:"	参考答案：ABD	"},
                    {title:"	测试人员对于产品的业务分析通常包含哪些步骤	", option:"	A:理解产品B:识别范围C:细化流程D:提炼重点	", out:"	参考答案：ABCD	"},
                    {title:"	git删除分支的命令是？	", option:"	A:gitbranch–DdevB:rmdevC:gitrmdevD:gitbranch–ddev	", out:"	参考答案：AD	"},
                    {title:"	质量红线流程中以下正确的	", option:"	A:发布后不执行线上验证B:严禁发布后没有对应的回滚方案；C:线上配置经验证后全网推送D:代码未经测试或未经开发自测发布上线；	", out:"	参考答案：BC	"},
                    {title:"	aone上创建代码变更一般管理哪些业务	", option:"	A:开发时间变更B:紧急发布C:人员变更D:日常的发布	", out:"	参考答案：BD	"},
                    {title:"	以下哪些缺陷类型归属于开发责任的编码相关缺陷？	", option:"	A:修复测试用例B:日志问题C:安全缺陷D:客户端视觉问题	", out:"	参考答案：BCD	"},
                    {title:"	任何人都可以在任意项目的迭代中查看缺陷	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	linke推进到集成阶段步骤：1进入迭代详情。2点击 “完成开发阶段”3确保符合检查条件， 如果不符合条件，请根据指示逐个解决。4 点击 “完成开发阶段”。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	通过PMD扫描发现存在PMD阻断与严重问题，未修复也可直接上线	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	数据设计的三板斧包括？	", option:"	A:头脑风暴模型B:逻辑数据模型C:物理数据设计D:概念数据模型	", out:"	参考答案：BCD	"},
                    {title:"	开发人员可根据分支流地址，通过什么工具进行代码下载，开始进行编码工作。	", option:"	A:svnB:TcenterC:aoneD:git	", out:"	参考答案：AD	"},
                    {title:"	质量红线需关注（）	", option:"	A:findbugsB:白盒扫描C:黑盒扫描D:PMD	", out:"	参考答案：ABCD	"},
                    {title:"	关于质量红线以下说法正确的是	", option:"	A:资损防控：事前验证分析（可以合并到测试分析中），事中监控：需要部署哪些实时监控，核对脚本，事后应急：止血方案，资金应急处理方案B:明确是典型故障的，如果再发生同类问题即触犯质量红线C:质量红线：我们产品交付给用户的质量底线D:典型故障：线上缺陷分析库中定期挑选出典型的问题放到商家技术学院质量专题下面，并给出典型特征，当然所有同学都可以在专区下面发表评论来讨论是否是典型问题，规避措施，建议等	", out:"	参考答案：ABCD	"},
                    {title:"	分支合并主干后，开发可以随时提交代码。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	以下哪个选项不是需求阶段重要产出物？	", option:"	A:测试文档B:产品需求文档C:标准项目安全分析报告D:白板设计	", out:"	参考答案：A	"},
                    {title:"	Aone平台有哪些功能？	", option:"	A:项目质量分析B:代码权限管理C:需求跟踪D:需求管理	", out:"	参考答案：ABCD	"},
                    {title:"	风险规避中三板斧包含下列哪些选项？	", option:"	A:可灰度B:可跳过C:可监控D:可回滚	", out:"	参考答案：ACD	"},
                    {title:"	git中下列说法正确的是？	", option:"	A:当git无法自动合并分支时，就必须首先解决冲突。解决冲突后，再提交，合并完成.B:合并某分支到当前分支：gitmergeC:删除分支：gitbranch-dD:提交代码：gitpull	", out:"	参考答案：ABC	"},
                    {title:"	创建需求是在一下那个系统中进行？	", option:"	A:伙伴B:AoneC:tcenterD:语雀	", out:"	参考答案：B	"},
                    {title:"	红线质量中哪几项表明sit测试已完成？	", option:"	A:findbugs未修复为0B:分支CI用例通过率100%C:黑盒无未修复问题D:白盒无未修复问题	", out:"	参考答案：ABCD	"},
                    {title:"	蚂蚁项目有哪些数据库？	", option:"	A:TEST（SIT）B:生产C:代码源D:DEV	", out:"	参考答案：ABD	"},
                    {title:"	antx配置变更操作正确的是（）	", option:"	A:提交完antx配置变更任务以后，可以在项目的关联任务下找到B:新增antx配置只允许新增私有配置C:通过新建配置项变更进入antx配置变更页面D:提交的antx变更任务未完成的情况，会影响项目合并	", out:"	参考答案：ACD	"},
                    {title:"	用git diff可以查看修改内容	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	git merge和git rebase都可以将其他分支的修改合并到当前分支？	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	把文件往Git版本库里添加的时候只需要git add就行？	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	GIT仓库使用描述正确的是	", option:"	A:往GIT仓库新增文件的时候，操作步骤为先使用命令gitaddxxx文件，然后使用命令gitcommitB:gitcheckout表示切换另一个分支，gitcheckout--file表示把file文件在工作区的修改全部撤销。C:修改后的内容要提交到GIT，只需使用命令gitcommitD:gitdiff可以查看修改内容	", out:"	参考答案：ABD	"},
                    {title:"	产品发布后可以没有对应的回滚方案。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	把文件添加到仓库需要用到哪些命令？	", option:"	A:gitinitB:gitcheckoutC:gitcommitD:gitadd	", out:"	参考答案：CD	"},
                    {title:"	紧急情况下，不关键的功能代码直接在线上测试就可以了	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	风险识别中主要需要识别出哪些风险？（包括但不限于）	", option:"	A:资损风险B:安全性风险C:稳定性风险D:不可能出现风险	", out:"	参考答案：ABC	"},
                    {title:"	关于git以下说法正确的是	", option:"	A:注意gitconfig命令的--global参数，用了这个参数，表示你这台机器上所有的Git仓库都会使用这个配置B:git是分布式版本控制系统，同一个git仓库，可以分布到不同的机器上C:MAC上，可以先安装homebrew，然后通过homebrew安装gitD:版本库又名仓库，英文名repository，你可以简单理解成一个目录，这个目录里面的所有文件都可以被Git管理起来，每个文件的修改、删除，Git都能跟踪，以便任何时刻都可以追踪历史，或者在将来某个时刻可以“还原”。	", out:"	参考答案：ABCD	"},
                    {title:"	git中，还从来没有被添加过文件状态是Untracked。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	aone上创建权限工单的入口在哪？	", option:"	A:更多流程中B:页面右上角的＋C:用例D:任务	", out:"	参考答案：AB	"},
                    {title:"	以下案例，责任归属于开发的有	", option:"	A:aone的配置项变更没有提交，或者配置项变更填写错误引起的。再就是服务器编码格式不对导致编译不了，或者DRM配置没有推初始化数据B:react路由配置、静态文件发布系统配置，设计公用的CSS、js引用错误地址之类的C:服务器发布多台机子的时候有概率其中有一两台发布失败，而导致代码不统一D:服务器启动的时候，由于磁盘占满，导致日志无法写入，服务器启动不了	", out:"	参考答案：AB	"},
                    {title:"	跨线项目中，以下对项目主测分说法正确的有	", option:"	A:明确职责划分B:明确业务涉众C:推动跨线评估	", out:"	参考答案：ABC	"},
                    {title:"	linke 申请研发服务器步骤：1进入迭代详情，2在操作菜单区点击 “申请服务器”，3点击 “申请” 按钮	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	以下关于线下缺陷等级，描述正确的是：	", option:"	A:线下缺陷等级-Normal（普通级）例如页面错别字、样式、错误提示用语、日志不完整等细节点的缺陷B:线下缺陷等级-Trivial（细小级）例如数据不完整、重复提交、字段长度限制导致报错、校验等C:线下缺陷等级-Major（主要级）例如重要功能上的功能失败，但不影响主流程的缺陷D:线下缺陷等级-Blocker（阻碍级）例如主流程走不下去，无法继续测试的缺陷	", out:"	参考答案：CD	"},
                    {title:"	在ANONE使用过程中，以下说法不正确的是	", option:"	A:新建缺陷必须要设置解决者B:新建数据库变更不需要关联代码变更C:当变更走到已合并状态下，可以提交预发布申请D:新建配置项变更之前，必须关联发布	", out:"	参考答案：B	"},
                    {title:"	质量发布标准必须具备哪几项	", option:"	A:交付内容B:研发分析文档C:codereviewD:测试完成度	", out:"	参考答案：ABCD	"},
                    {title:"	测试范围评估一般需要进行哪些分析	", option:"	A:功能点分析，对新增、改动点进行业务分析B:非功能性分析，通常包括安全性、兼容性、可靠性等等C:影响点分析，分析影响范围，涉及核心公共组件或方法的改动，还要评估对其他系统和产品的影响	", out:"	参考答案：ABC	"},
                    {title:"	交付报告中必须要的结果包含哪些内容？	", option:"	A:codereview结果B:整体代码覆盖率结果C:变更代码覆盖率结果D:测试通过结果	", out:"	参考答案：ACD	"},
                    {title:"	怎么在SOFA工程中新建SOFA4模块	", option:"	A:现有SOFA工程的根目录中，右键，选择「New-->Directory」B:现有SOFA工程的根目录中，右键，选择「New-->Module」C:现有SOFA工程的根目录中，右键，选择「New-->File」D:现有SOFA工程的根目录中，右键，选择「New-->DataSource」	", out:"	参考答案：B	"},
                    {title:"	sofa-config.properties 配置文件在哪个目录下	", option:"	A:assemblyB:confC:appD:webroot	", out:"	参考答案：B	"},
                    {title:"	sofa-config.properties中配置项rpc_tr_port表示TR端口号的配置，端口号默认为	", option:"	A:12203B:12201C:12204D:12200	", out:"	参考答案：D	"},
                    {title:"	Biz 层依赖Core层的哪个模块来为其提供核心领域服务	", option:"	A:core-utilB:core-modelC:core-daD:core-service	", out:"	参考答案：D	"},
                    {title:"	SOFA 4 的文档地址位于	", option:"	A:https://lark.alipay.com/middleware/sofa4B:http://doccenter.jr.alipay.net/docs/cn/middleware/framework/mvc3/index.htmlC:https://lark.alipay.com/middleware/sofa-mvc4D:http://doccenter.jr.alipay.net/docs/cn/middleware/framework/sofamvc/index.html	", out:"	参考答案：A	"},
                    {title:"	线程被回收的空闲时间，是在sofa-config.properties中哪个配置配项里配置	", option:"	A:rpc_transmit_urlB:rpc_ws_openC:rpc_transmit_url_timeout_trD:jetty_threadpool_max_idle_time_ms	", out:"	参考答案：D	"},
                    {title:"	提供给外部系统使用的接口的定义在common层的哪个模块	", option:"	A:common-service-facadeB:common-dalC:common-daD:common-util	", out:"	参考答案：A	"},
                    {title:"	SOFA工程启动是否成功，windows用户用以下哪个地址来测试	", option:"	A:http://localhost:8080/sample.htmB:http://localhost:7777/sample.htmC:http://localhost:8090/sample.htmD:http://localhost/sample.htm	", out:"	参考答案：D	"},
                    {title:"	SOFA module配置是dev的profile模块才能够被激活的命令是	", option:"	A:sofa_profiles_active=devB:spring_profiles_active=devC:sofa_runtime_profiles_active=devD:spring_runtime_profiles_active=dev	", out:"	参考答案：C	"},
                    {title:"	以下说法错误的是？	", option:"	A:禁止使用GET请求来完成数据的添加，修改，删除等功能。但如果业务需求必须要用GET请求来实现，请保证此请求有相应的验证措施，如DSA签名等B:对于文件上传的实现，必须统一使用sofamvc框架提供的SecurityMultipartResolver类C:高敏感数据只可以在内部日志系统中打印D:使用白名单限制跳转的url可以防范页面跳转漏洞	", out:"	参考答案：C	"},
                    {title:"	插件升级，手动升级时检查版本更新的菜单是在	", option:"	A:智能研发->插件管理B:智能研发->问题排查C:智能研发->小工具D:智能研发->SOFA	", out:"	参考答案：A	"},
                    {title:"	ACF 权限问题，如果在应用在配置 objectDefinitionSource 来做 ACF 的权限，需要注意 objectDefinitionSource 这个 Bean 放在 哪里才有效	", option:"	A:META-INF/spring/*.xml中B:MERGE-INF/*.xml中C:MERGE-INF/Spring/*.xml中D:META-INF/init/*.xml中	", out:"	参考答案：B	"},
                    {title:"	Sofa 提供组件容器有诸多的好处，其中说法错误的是	", option:"	A:管理整个组件的生命周期B:提供组件的健康检查能力C:提供统一的编程模型D:提供代码自检能力	", out:"	参考答案：D	"},
                    {title:"	Cloudengine 默认的 Telnet 端口为	", option:"	A:8080B:8341C:1234D:3306	", out:"	参考答案：C	"},
                    {title:"	以下说法错误的是	", option:"	A:可以查看logs/sofa/sofa-startup.log来查看SOFA模块的启动信息B:SofaRPC上下文是存在ThreadLocal中的临时数据C:每个SOFA模块的META-INF/spring目录下，只能放置一个Spring配置文件D:可以通过使用ser命令查看已经发布的服务以及类型	", out:"	参考答案：C	"},
                    {title:"	敏感信息日志打印规范描述不正确的是	", option:"	A:日志中打印信用卡CVV2/CVC2的信息B:日志中打印密码、口令、密钥等信息C:身份证信息不加密的情况下，直接打印在日志里D:邮箱、地址没有特殊要求的情况下可以直接打印在日志里，无需加密	", out:"	参考答案：ABC	"},
                    {title:"	使用sofa的好处有	", option:"	A:管理整个组件的生命周期B:提供组件的健康检查能力C:提供统一的编程模型D:强大的应用程序的模块化的能力	", out:"	参考答案：ABCD	"},
                    {title:"	sofa集成的测试框架有哪些？	", option:"	A:EasybB:JUnit4C:JUnit3D:TestNG	", out:"	参考答案：BCD	"},
                    {title:"	以下哪些属于敏感数据，是不可以泄露的	", option:"	A:买家身份证号码B:域账号和密码C:交易信息，如交易金额D:写了祝福语的贺卡E:企业工商注册信息	", out:"	参考答案：ABCE	"},
                    {title:"	以下关于SOFA 的组件的状态说法正确的是	", option:"	A:Resolved：表示组件已经完成解析B:Activated：表示组件已经被激活C:Registered：表示组件已经注册到SOFA的组件运行时中D:SOFA的组件其实有三种状态	", out:"	参考答案：ABCD	"},
                    {title:"	SOFA 提供了两种形式的服务发布和引用，以下说法正确的是()	", option:"	A:RPC服务发布和引用：解决多个SOFA应用之间模块的调用问题B:JVM服务发布和引用：解决多个SOFA应用内部模块之间的调用问题C:JVM服务发布和引用：解决一个SOFA应用内部模块之间的调用问题D:RPC服务发布和引用：解决一个SOFA应用之间模块的调用问题	", out:"	参考答案：AC	"},
                    {title:"	下列说法正确的是	", option:"	A:敏感数据在传输过程中需要进行加密，请使用HTTPS传输敏感数据，或者采用其他安全的加密算法。B:银行卡有效期不属于敏感信息C:所有系统特权帐号和口令都是敏感信息，包括自己的dev开发机D:在后台Controllerjava文件中，需要在处理对应POST请求的函数之前添加注解@Form。其中@Form有两个参数：lisCsrfCheck，true表示需要进行CSRF验证，false表示不进行CSRF验证。lisRepeatCheck，ture表示防重复提交，false表示不防重复提交。	", out:"	参考答案：ACD	"},
                    {title:"	git checkout --file是切换到file分支的意思。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	SOFA 项目分成五层，分别是 test、web、biz、core、common，在项目构建中，缺一不可	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	biz层中biz-util模块与web层中的web-home对应	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	common-dal模块相当于传统分层中的数据访问层，封装了对数据库的访问逻辑，向上暴露DAO服务，他通常是定义在核心领域层中？	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	sofa-config.properties中配置项rpc_max_pool_size_tr是配置TR 服务器线程池最大线程数	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	sofa-config.properties中配置项run_mode是用来配置RPC 运行模式	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	在一个 SOFA 应用中，应用中的每一个模块都含有各自的 Spring 上下文，模块之间的调用通过本地服务的方式来完成	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	Common层的common-dal封装了对数据库的访问逻辑	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	在ibatis中写SQL语句时，不要使用$*$的方式，最好使用#*#绑定变量。是否正确？	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	SOFA应用增加依赖时，除了在pom.xml中增加dependency，还需要在assembly/pom.xml 也增加对应的依赖()	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	如果只开发纯业务的核心系统可以去掉sofa工程目录中的哪一层	", option:"	A:bizB:coreC:webD:test	", out:"	参考答案：C	"},
                    {title:"	maven查看项目依赖情况的命令是	", option:"	A:mvnjetty:runB:mvnproject-info-reports:dependenciesC:mvndependency:resolveD:mvndependency:analyze	", out:"	参考答案：C	"},
                    {title:"	sofa-config.properties中配置项jetty_threadpool_max_size默认的线程最大数是	", option:"	A:100B:90C:200D:300	", out:"	参考答案：D	"},
                    {title:"	SOFA工程启动是否成功，mac用户用以下哪个地址来测试	", option:"	A:http://localhost/sample.htmB:http://localhost:8090/sample.htmC:http://localhost:8080/sample.htmD:http://localhost:7777/sample.htm	", out:"	参考答案：D	"},
                    {title:"	以下哪些说法是错误	", option:"	A:sofa不能管理整个组件的生命周期B:SOFA运行在Cloudengine分布式应用容器之上C:SOFA为应用程序带来了SOA化的模块化架构；并且提供了一个组件运行时，可以对应用的组件进行管理D:SOFA源自于ServiceOrientedFabricArchitecture，即面向服务的架构	", out:"	参考答案：A	"},
                    {title:"	Biz 层依赖Core层的哪个模块来定义模型对象	", option:"	A:core-utilB:core-daC:core-serviceD:core-model	", out:"	参考答案：D	"},
                    {title:"	sofamvc编码规范里下列说法错误的是？	", option:"	A:段代码各语句之间有实质性关联并且是完成同一件功能的，那么可考虑把此段代码构造成一个新的方法。B:代码修改的同时，注释可以不用进行相应的修改C:如果使用要if-elseif-else方式表达逻辑请勿超过3层D:所有的枚举类型字段必须要有注释，说明每个数据项的用途	", out:"	参考答案：B	"},
                    {title:"	SOFA工程项目结构中，一般位于依赖最顶层的是哪个？	", option:"	A:核心领域层B:业务层C:展现层D:测试层	", out:"	参考答案：D	"},
                    {title:"	哪个目录下定义了如何将一个工程打包成一个 SOFA .ace 发布包的过程	", option:"	A:assemblyB:confC:bizD:app	", out:"	参考答案：A	"},
                    {title:"	框架升级后，本地运行报错：java.lang.NoClassDefFoundError: org/quartz/impl/JobDetailImpl的解决方式是	", option:"	A:删除quartz2依赖B:需要在test模块增加quartz1依赖，同时mvndependency:tree，分析下依赖树，排除所有quartz1的依赖C:需要在test模块增加quartz2依赖，同时mvndependency:tree，分析下依赖树，排除所有quartz3的依赖D:需要在test模块增加quartz2依赖，同时mvndependency:tree，分析下依赖树，排除所有quartz1的依赖	", out:"	参考答案：D	"},
                    {title:"	SOFA工程项目结构图分为以下几层()	", option:"	A:测试层B:核心领域层C:业务层D:展现层E:基础层	", out:"	参考答案：ABCDE	"},
                    {title:"	关于spring安全编码规范说法正确的是	", option:"	A:CSRF是伪造客户端请求的一种攻击B:SQL注入是通过将构造的SQL命令作为数据提交到web服务器，web服务器对这些数据没有适当的处理，而交给数据库服务器执行，导致攻击的发生C:表单篡改是由于部分开发工程师习惯使用form表单中的hidden域传递参数，这些参数中不乏金额、账号等关键数据，而这些数据是可以在客户端修改之后，再提交服务器的。因此，导致了表单数据被篡改。D:XSS是恶意攻击者往Web页面里插入恶意html代码，当用户浏览该页之时，嵌入其中Web里面的html代码会被执行，从而达到恶意攻击用户的特殊目的。	", out:"	参考答案：ABCD	"},
                    {title:"	sofa框架打包发布时core目录和lib目录下的jar包有什么区别	", option:"	A:core目录下jar包不会计算依赖关系B:lib目录下jar包不会计算依赖关系C:core目录下jar包会计算依赖关系D:lib目录下jar包会计算依赖关系	", out:"	参考答案：BC	"},
                    {title:"	编码过程中需要防范的漏洞都包含哪些？	", option:"	A:防范表单数据篡改B:防范SQL注入漏洞C:防范CSRF漏洞D:防范XSS漏洞	", out:"	参考答案：ABCD	"},
                    {title:"	rpc/sofa-router.log：SOFARouter 相关日志，无标准格式	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	tracelog/rpc-profile.log：SOFA RPC 处理性能日志	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	sofa-config.properties中配置项rpc_min_pool_size_tr是配置TR 服务器线程池最小线程数	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	#SXML在VM中表示输出XML的变量数据，特殊情况下也可以输出其他变量。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	sofa-config.properties中配置项rpc_tr_reconnect_period是用来配置TR客户端会自动重连已断连的服务端的时间间隔	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	sofa-config.properties中配置项rpc_transmit_url是用来配置预热与权重配置	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	目前SOFA集成测试框架集成了JUnit和TestNG，对于JUnit，又提供了JUnit3和JUnit4 两种风格，其中JUnit4的风格需要继承JunitEclipseSofaTest	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	Biz 层依赖Core层的core-service来为其提供核心领域服务	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	sofa工程项目结构中core层可以看到项目中的所有模块	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	sofa服务发布第一步是做什么？	", option:"	A:直接启动服务B:对服务进行封装C:定义服务接口D:实现服务接口	", out:"	参考答案：C	"},
                    {title:"	RPC 服务处理性能日志打印阈值是在sofa-config.properties中的那个配置项里面配置	", option:"	A:rpc_transmit_urlB:rpc_profile_threshold_trC:rpc_transmit_url_timeout_trD:jetty_threadpool_max_idle_time_ms	", out:"	参考答案：B	"},
                    {title:"	在编程中以下哪个命名是合理的	", option:"	A:_a_objectB:DaZhePromotionC:$a_objectD:a_come_object	", out:"	参考答案：D	"},
                    {title:"	SOFA 中获取到 sofa-config.properties 里面的配置，可以使用下列哪个接口	", option:"	A:HttpMessageConverterB:HandlerInterceptorC:AppConfigurationAwareD:HandlerExceptionResolver	", out:"	参考答案：C	"},
                    {title:"	biz层中哪个模块与web层中的web-home对应	", option:"	A:biz-utilB:prode2C:biz-sharedD:pord1	", out:"	参考答案：C	"},
                    {title:"	是否开启 WS 的功能，是在sofa-config.properties中哪个配置配项里配置	", option:"	A:rpc_profile_threshold_trB:rpc_transmit_urlC:rpc_transmit_url_timeout_trD:rpc_ws_open	", out:"	参考答案：D	"},
                    {title:"	SOFA项目工程一共分几层	", option:"	A:4B:5C:6D:3	", out:"	参考答案：B	"},
                    {title:"	编写测试用例，怎么排除不想启动的模块	", option:"	A:在XConfigure注解中添加excludeBundles属性B:在XConfigure注解中删除除excludeIde外的属性C:在XConfigure注解中删除excludeIde属性D:在XConfigure注解中添加excludeIde属性	", out:"	参考答案：A	"},
                    {title:"	所有 Biz 层模块都依赖于() ，且通过它间接依赖 core 层和 common 层	", option:"	A:biz-service-implB:web层C:core层D:biz-shared	", out:"	参考答案：D	"},
                    {title:"	git提交代码需要如下的那几个步骤？	", option:"	A:gitcommit-m注释B:gitpushC:gitadd文件D:gitpull	", out:"	参考答案：ABC	"},
                    {title:"	防范敏感数据泄露，以下哪些属于敏感数据	", option:"	A:会员EMAIL、支付宝帐号B:用户个人地址、联系方式C:银行卡卡号D:身份证信息	", out:"	参考答案：ABCD	"},
                    {title:"	使用纯注解发布一个SOFA服务并引用，需要用到哪些注解？	", option:"	A:SofaReferenceB:SofaServiceC:ControllerD:Serivce	", out:"	参考答案：ABD	"},
                    {title:"	SOFA中的工程都是标准的maven工程，其中META-INF目录下的MANIFEST.MF文件记录了工程元数据，spring目录下存放由spring管理的配置文件？	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	可以使用GET请求来完成数据的添加，修改，删除等功能。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	SOFA提供的 TR调用， 使用的底层通信框架 TBRemoting。相对于 WS，TR 支持更加复杂的对象，序列化后的对象更小，占用的带宽更小，其默认端口是12000？	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	rpc/rpc-remoting.log：网络层日志，无标准格式	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	在一个model里不能调用其他model里的effects方法	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	在Aone上申请开发服务器，用于调试自己提交的代码，启动日志存放在/home/admin/logs/应用名/sofa/目录下	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	Biz 层依赖Core层的core-util来定义模型对象	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	关于maven版本问题，CloudEngine 4.3.0.0 以上不一定需要使用maven3进行编译	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	提供给外部系统使用的接口的定义在common层的common-service-façade模块	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	为了防止SQL注入攻击，变量绑定应该使用哪种方式	", option:"	A:%*%B:$*$C:&*&D:#*#	", out:"	参考答案：D	"},
                    {title:"	用什么命令查看git 版本，加上--pretty=oneline参数查看关键信息	", option:"	A:gitdiffB:gitlogC:gitaddD:gitstatus	", out:"	参考答案：B	"},
                    {title:"	业务系统启动加载了哪些业务模块，其依赖的模块是否被正常加载，通过哪个日志察看	", option:"	A:sofa-boot.logB:sofa-healthcheck.logC:cloudengine-boot.logD:sofa-startup.log	", out:"	参考答案：D	"},
                    {title:"	maven发布命令，将打包的文件发布到远程参考	", option:"	A:mvnjetty:runB:mvndependency:resolveC:mvndeployD:mvndependency:analyze	", out:"	参考答案：C	"},
                    {title:"	框架升级后，javassist 出现 invalid constant type: 18的错误原因是	", option:"	A:javassist的版本过高，无法在JDK8下使用B:javassist的版本过低，无法在JDK6下使用C:javassist的版本过低，无法在JDK8下使用D:JDK8没有安装	", out:"	参考答案：C	"},
                    {title:"	以下哪个git命令是用来比较两个本地分支不同的内容	", option:"	A:gitdiffborigin/b--statB:gitdiff--statC:gitdiffb1b2--statD:gitdiff--stat	", out:"	参考答案：C	"},
                    {title:"	以下说法哪些是正确的	", option:"	A:重要标识，比如用户登录次数不要写在Cookie中，要写在Session或者数据库中。B:对称加密算法不要使用DES（甚至base64编码），使用3DES、AES；非对称加密算法使用RSA、ECC；签名算法不要使用MD5+SecurityCode，使用RSA或者DSA。C:对于文件上传的实现，请统一使用sofamvc框架提供的SecurityMultipartResolver类。要对上传文件的类型进行限制，限制的方式可以使用黑名单与白名单。D:如果需要对用户访问页面的流程进行限制，请使用页面流逻辑控制，比如webflow。	", out:"	参考答案：ABD	"},
                    {title:"	以下说法正确的是	", option:"	A:biz层给领域层需要协作的各个领域服务协调任务、委派工作，处理核心业务规则B:web-home是Web层中的公用Web模块，它包含了运行视图层需要的所有公共组件的配置，是SOFAMVC能正常运行的基础C:测试层位于依赖链的最底层，所有模块都会直接或间接的依赖它	", out:"	参考答案：AB	"},
                    {title:"	用户个人敏感数据的定义包括哪些信息？	", option:"	A:电话号码B:邮箱相关C:密码相关D:银行卡相关	", out:"	参考答案：ABCD	"},
                    {title:"	confreg/config.client.log：配置中心客户端日志	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	rpc/rpc-default.log：SOFA RPC INFO/WARN 日志，无标准格式	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	sofa-config.properties中配置项rpc_transmit_url_timeout_tr是用来配置预热调用超时时间，单位毫秒	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	rpc/rpc-remoting-serialization.log：网络层序列化日志，无标准格式	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	升级 SOFA4 之后 zmode=false 无效的原因是业务方没有修改 jbossctl.sh	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	根据命名规范 ，BIZ层服务类以什么结尾	", option:"	A:以Facade结尾B:以Service结尾C:以Util结尾D:以Manager结尾	", out:"	参考答案：D	"},
                    {title:"	开启序列化安全黑名单是在sofa-config.properties哪个配置选项中配置	", option:"	A:rpc_profile_threshold_trB:rpc_tr_serialize_blacklistC:rpc_max_address_wait_timeD:jetty_threadpool_max_idle_time_ms	", out:"	参考答案：B	"},
                    {title:"	sofa-config.properties中配置项jetty_threadpool_min_size默认的线程最小数是	", option:"	A:90B:200C:100D:300	", out:"	参考答案：A	"},
                    {title:"	sofa工程项目结构中test层的主要作用是	", option:"	A:核心代码封装B:应用逻辑封装C:视图扩展D:提供单元测试的基类，供开发人员继承或扩展	", out:"	参考答案：D	"},
                    {title:"	用git的什么命令可以知道修改什么文件	", option:"	A:gitlogB:gitaddC:gitstatusD:gitdiff	", out:"	参考答案：C	"},
                    {title:"	Spring 配置文件的velocity变量从哪里读取？	", option:"	A:drmB:jvm启动参数C:bizD:sofa-config.properties	", out:"	参考答案：D	"},
                    {title:"	以下哪些说法是错误？	", option:"	A:SOFACore工程可以通过stoWeb命令转换成一个SOFAWeb工程B:SOFA只能通过注解的方式获取到sofa-config.properties里面的配置C:SOFA框架本身提供了一系列的配置项，这些配置项可以在sofa-config.properties文件中进行配置D:SOFA提供了XML、Annotation、编程API三种方式给开发人员来发布JVM服务和引用JVM服务	", out:"	参考答案：B	"},
                    {title:"	针对 SOFA 应用程序的生命周期，SOFA 提供了启动完成的回调接口有	", option:"	A:ApplicationStartupCallbackB:ApplicationStartCallbackC:ApplicationStopCallbackD:ApplicationShutdownCallback	", out:"	参考答案：AD	"},
                    {title:"	sofa-config.properties中配置项rpc_enabled_ip_range是用来配置服务器绑定本地 IP 范围	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	sofa-config.properties中配置项rpc_pool_pre_start是配置TR 服务器线程池是否提前初始化核心线程池	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	SOFA项目的conf 目录下存放了应用的各种配置文件，包括 sofa-config.properties，log4j.xml，java_opts，如果是 Web 应用，还包括 nginx 的配置文件。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	sofa-config.properties中配置项rpc_pool_queue_size_tr是配置TR 服务器线程池队列大小	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	SOFA系统启动完成后，可以通过sofa-boot.log查看加载了哪些业务模块，也包括依赖的模块是否有异常	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	启动日志存放在业务日志更深一层的目录，/home/admin/logs/应用名/sofa/。例如kbopenprod的，那就是/home/admin/logs/kbopenprod/sofa/。主要看的是sofa-startup.log。具体需要开发去定位问题。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	将一个工程打包成一个 SOFA .ace 发布包的在以下哪个xml中有定义	", option:"	A:conf.xmlB:ant.xmlC:assembly目录下的pom.xmlD:pom.xml	", out:"	参考答案：C	"},
                    {title:"	建立起SOFA工程后，选择哪个命令来启动SOFA工程	", option:"	A:CreateSOFAApplicationB:DebugSOFAApplicationC:RunSOFAApplicationD:MakeSOFAApplication	", out:"	参考答案：C	"},
                    {title:"	SOFA工程结构中biz层是作用是什么	", option:"	A:展现层B:业务应用逻辑封装C:提供基础服务D:核心模块封装	", out:"	参考答案：B	"},
                    {title:"	如果想配置线程池最大线程数，应该修改sofa-config.properties的哪个属性	", option:"	A:tr_min_pool_sizeB:jetty_threadpool_max_sizeC:jetty_threadpool_min_sizeD:jetty_threadpool_max_idle_time_ms	", out:"	参考答案：B	"},
                    {title:"	sofamvc编码规范下列哪个Map类集合K/V均允许存储null值？	", option:"	A:TreeMapB:ConcurrentHashMapC:HashtableD:HashMap	", out:"	参考答案：D	"},
                    {title:"	对于防范SQL注入漏洞的描述正确的是	", option:"	A:SQL注入，就是通过将构造的SQL命令作为数据提交到web服务器，web服务器对这些数据没有适当的处理，而交给数据库服务器执行，导致攻击的发生。B:防范SQL注入，必须使用#*#绑定变量C:也可以使用$*$的方式绑定变量D:如果不防范，会导致数据库资料被窃取、修改或者删除，服务器被攻击者控制。	", out:"	参考答案：ABD	"},
                    {title:"	与外部系统交互的模块包含在common层中，当外部系统引用本系统的服务时，需要添加对该common-service-facade模块的依赖？	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	sofa-config.properties中配置项rpc_tr_port是用来配置TR 端口号	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	在https协议的页面，不要用<script、<img、<iframe、<frame、<frameset、<link等tag引入http协议的页面元素。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	以下和git分支有关的命令错误的是	", option:"	A:gitbranch<name>B:gitcheckout-b<name>C:gitcheckout<name>D:gitbranch-b<name>	", out:"	参考答案：D	"},
                    {title:"	发布服务是，当被 SofaService 注解的类实现了多个接口，通过SofaService的什么字段指定服务接口？	", option:"	A:interfaceB:typeC:interfaceType	", out:"	参考答案：C	"},
                    {title:"	biz层（业务应用层）依赖哪一层	", option:"	A:test层B:core-modelC:web-homeD:core-service	", out:"	参考答案：D	"},
                    {title:"	GET请求仅应该被用于获取信息。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	使用git时可以不用创建本地仓库	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	SOFA中增加依赖时，需要在哪个XML文件里面也要增加对应的依赖？	", option:"	A:assembly/pro.xmlB:parent.xmlC:ccbin/conf.xmlD:assembly/conf.xml	", out:"	参考答案：B	"},
                    {title:"	Common层的哪个模块封装了对数据库的访问逻辑	", option:"	A:util-daB:common-utilC:utilD:common-dal	", out:"	参考答案：D	"},
                    {title:"	Sofa mvc中集成的xss过滤框架是在velocity中对输出变量进行了防xss的处理，处理措施包括编码转义和过滤。以下属于框架中提供的的输出变量的方法有？	", option:"	A:#SJSB:#SHTMLC:#SXMLD:#SURL	", out:"	参考答案：ABCD	"},
                    {title:"	tracelog/rpc-server-digest.log：SOFA RPC 调用服务端摘要日志	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	可以使用拼音与英文混合的命名方式。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	sofa-config.properties中配置项sofa_runtime_local_mode是用来配置本地优先调用开关	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	git查看配置信息命令是否正确（git config --list）	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	哪一层可以放一些全局的处理逻辑，比如首页访问请求出炉、全局错误处理等	", option:"	A:业务应用层B:测试层C:核心领域层D:展现层	", out:"	参考答案：D	"},
                    {title:"	根据命名规范，Core层服务的命名以什么结尾	", option:"	A:以Data结尾B:以Util结尾C:以Service结尾D:以Core结尾	", out:"	参考答案：C	"},
                    {title:"	关于spring安全编码规范以下说法错误的是	", option:"	A:站内请求，允许使用GET请求来完成数据的添加，修改，删除等功能B:敏感数据在传输过程中需要进行加密，请使用HTTPS传输敏感数据，或者采用其他安全的加密算法。C:Sofamvc框架目前对POST和GET方式提交的请求都进行CSRF防御。D:编写ibatis的sqlxml时，不要用$*$的方式绑定变量，这种方式即使使用SQLMAP也会出现SQL注入漏洞，必须使用#*#绑定变量，进行预编译处理。	", out:"	参考答案：AC	"},
                    {title:"	cloudengine启动的时候首先会创建自己的日志，主要在/home/admin/logs/cloudengine目录下，其中启动过程有异常日志是打在 cloudengine-error.log中？	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	所有编程相关的命名均不能以下划线或美元符号开始。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	common-service-façade模块提供了系统调用其他应用相关服务的接口，	", option:"		", out:"		"},
                    {title:"	common-service-integration模块包含了系统对外提供的服务接口。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	根据命名规范，Core层服务的命名Data结尾	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	项目分层的 test、web、biz、core、common 五个子目录是在哪个目录下	", option:"	A:confB:assemblyC:appD:pom	", out:"	参考答案：C	"},
                    {title:"	代码中获取 sofa-config.properties 中的配置信息的方式	", option:"	A:使用Configuration注解B:实现AppConfigurationAware接口C:使用AppConfig注解D:使用Configurable注解	", out:"	参考答案：BC	"},
                    {title:"	关于spring安全编码规范一下说法错误的是	", option:"	A:站内请求，允许使用GET请求来完成数据的添加，修改，删除等功能B:敏感数据在传输过程中需要进行加密，请使用HTTPS传输敏感数据，或者采用其他安全的加密算法。C:Sofamvc框架目前对POST和GET方式提交的请求都进行CSRF防御。D:编写ibatis的sqlxml时，不要用$*$的方式绑定变量，这种方式即使使用SQLMAP也会出现SQL注入漏洞，必须使用#*#绑定变量，进行预编译处理。	", out:"	参考答案：AC	"},
                    {title:"	git init命令用于初始化一个Git仓库	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	sofa-config.properties中配置项rpc_register_confreg_ignore是用来配置服务端是否发布服务端到配置中心，用于测试	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	sofa工程项目结构中哪一层可以看到项目中的所有模块	", option:"	A:bizB:coreC:webD:test	", out:"	参考答案：D	"},
                    {title:"	根据命名规范 ，BIZ包装门面以什么结尾	", option:"	A:以Service结尾B:以Manager结尾C:以Facade结尾D:以Util结尾	", out:"	参考答案：C	"},
                    {title:"	sofa结构除了（）外，每个层中都按业务或功能再做了模块上的划分	", option:"	A:核心领域层B:测试层C:应用层D:展现层	", out:"	参考答案：B	"},
                    {title:"	rpc/common-error.log：SOFA RPC 错误日志，无标准格式	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	SOFA框架中SofaReference注解用于发布一个服务。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	sofa-config.properties中配置项rpc_tr_heart_beat_interval是用来做什么的	", option:"	A:配置资源池大小B:配置TR心跳的间隔时间C:配置最大线程数量D:配置最小线程数量	", out:"	参考答案：B	"},
                    {title:"	IDEA时添加自定义的 Repository用哪个地址？	", option:"	A:http://ide.alipay.net/plugin/fileB:http://ide.alipay.net/plugin/listC:http://ide.alipay.net/plugin/dataD:http://ide.alipay.net/plugin/profile	", out:"	参考答案：B	"},
                    {title:"	在使用https作为传输协议的页面，如果引入了http协议传输的哪些元素，会导致某些浏览器会弹出安全警告？	", option:"	A:imgB:scriptC:iframeD:包含(但不限于)以上所有	", out:"	参考答案：D	"},
                    {title:"	每一个maven构件都需要有个坐标唯一标示，总POM的坐标最主要由groupId：反向域名方式加应用名、artifactId:唯一标示本模块id、version:版本在构建选项里生成，名称和url以及描述信息起到辅助定位和构建过程对模块的标示。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	sofa框架中，assembly 目录的 pom.xml 里面定义了如何将一个工程打包成一个 SOFA .ace 发布包的过程？	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	框架升级后，导致sofa4 xml标签标红的原因是IDEA没有寻找到正确的schema定义	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	以下哪个日志文件可以看到系统发布了哪些 SOFA 服务？	", option:"	A:cloudengine-boot.logB:sofa-boot.logC:sofa-startup.logD:sofa-healthcheck.log	", out:"	参考答案：B	"},
                    {title:"	rpc/tr-connection-digest.log：服务连接池日志，已废弃	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	sofamvc安全编码规范规定类名和接口使用完整的英文单词描述，每个英文单词的首字母使用大写、其余字母使用小写的大小写混合法。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	git新增配置信息命令是否正确（git config --levelName --add configName configValue）	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	SOFA 模块的 MANIFEST.MF 文件包括哪些信息	", option:"	A:Module-NameB:Require-ModuleC:Manifest-VersionD:Spring-Parent	", out:"	参考答案：ABCD	"},
                    {title:"	回退到上个版本可以使用的命令有()	", option:"	A:gitreset--hard版本号B:gitreset--HEAD^C:gitreset--hardHEAD^D:gitreset--hardHEAD版本号	", out:"	参考答案：AC	"},
                    {title:"	tracelog/rpc-client-digest.log：SOFA RPC 调用客户端摘要日志	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	sofa-config.properties中配置项rpc_profile_threshold_tr是用来配置RPC 服务处理性能日志打印阈值	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	sofa-config.properties中配置项jetty_threadpool_max_idle_time_ms的默认值是	", option:"	A:300B:30000C:300000D:3	", out:"	参考答案：B	"},
                    {title:"	git合并分支的命令是	", option:"	A:gitbranchB:gitcheckoutC:gitcombineD:gitmerge	", out:"	参考答案：D	"},
                    {title:"	执行数据库DML命令特别是update/insert/delete时，要注意影响数据条数	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	sofa-config.properties中配置项rpc_bind_network_interface是用来配置服务器绑定固定网卡	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	IDEA插件安装对版本有什么要求	", option:"	A:ntellijIDEA15以上B:ntellijIDEA15以下C:只能用ntellijIDEA15D:都可以	", out:"	参考答案：A	"},
                    {title:"	web层中通过哪个模块来间接依赖 biz、core 和 common 层。	", option:"	A:web-prod2B:web-homeC:web-prod1D:web-util	", out:"	参考答案：B	"},
                    {title:"	SOFA工程结构中哪个目录是用来存放相关配置的	", option:"	A:appB:confC:assemblyD:webroot	", out:"	参考答案：B	"},
                    {title:"	SOFA工程新建好了，需要重起ＩＤＥＡ	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	成功的测试是指运行测试用例后	", option:"	A:边界值分析B:循环覆盖C:判定覆盖D:路径覆盖	", out:"	参考答案：A	"},
                    {title:"	在客户端工具SecureCRT中，Antx.properties目录下是记录什么信息的	", option:"	A:用于下载代码、更新代码、编译和部署工程的脚本B:共享数据或者文件C:java源码D:记录一些服务的地址信息和配置信息	", out:"	参考答案：D	"},
                    {title:"	浏览器与Web服务器之间使用的协议是？	", option:"	A:HTTPB:SMTPC:SNMPD:DNS	", out:"	参考答案：A	"},
                    {title:"	为了提高测试的效率，应该：	", option:"	A:随机地选取测试数据B:在完成编码以后制定软件的测试计划C:取一切可能的输入数据作为测试数据D:选择发现错误的可能性大的数据作为测试数据	", out:"	参考答案：D	"},
                    {title:"	下列数据库服务器中，哪个是用于开发和测试的功能验证	", option:"	A:nHistory-apayB:ntestdbC:ndevdb	", out:"	参考答案：A	"},
                    {title:"	在支付宝的服务器中，编译项目的命令为	", option:"	A:deploy.shB:build.shC:mkview.shD:ccupdate.sh	", out:"	参考答案：B	"},
                    {title:"	PRD是指什么	", option:"	A:需求文档B:产品经理C:项目经理D:不清楚	", out:"	参考答案：A	"},
                    {title:"	测试需要执行的步骤不包括以下哪项	", option:"	A:测试计划B:需求串讲C:关联关系D:测试执行	", out:"	参考答案：B	"},
                    {title:"	工作中遇到问题是，首先应该如何处理	", option:"	A:立刻找师傅求救B:立刻把问题发送到讨论组C:忽略问题D:自己思考并尝试可能的解决方式	", out:"	参考答案：D	"},
                    {title:"	Sofa系统：错误日志文件名为:	", option:"	A:error_logB:common-error_logC:error.logD:common-error.log	", out:"	参考答案：D	"},
                    {title:"	有关“Hotpatch发布”描述正确的是	", option:"	A:用于特殊需求发布或修复线上紧急问题的工作空间B:对线上部分用户更新以验证新功能C:用于集成、灰度和发布的工作空间D:修复线上紧急问题的工作空间.	", out:"	参考答案：D	"},
                    {title:"	下面选项中，哪一个不是网络抓包工具	", option:"	A:LuaB:CharlerC:WiresharkD:Fiddler	", out:"	参考答案：A	"},
                    {title:"	./ccupdate.sh、./build.sh、./deploy.sh分别对应的是	", option:"	A:部署、编译、下载B:下载、编译、部署C:编译、部署、下载D:更新、编译、部署	", out:"	参考答案：D	"},
                    {title:"	数据库下列哪个命令，可以用来串接字符串？	", option:"	A:insertB:CONCATC:countD:select	", out:"	参考答案：B	"},
                    {title:"	创建stable环境的支付宝账号，数据环境应该选择以下哪种？	", option:"	A:沙箱环境B:稳定环境C:测试环境D:其他	", out:"	参考答案：B	"},
                    {title:"	伙伴带我处理中“被延迟到下个迭代修复的bug”的状态是：	", option:"	A:WontfixB:LaterC:DuplicateD:fixed	", out:"	参考答案：B	"},
                    {title:"	在Linux下，哪个命令可以查看当前文件路径？	", option:"	A:pwdB:lsC:cdD:ps	", out:"	参考答案：A	"},
                    {title:"	在伙伴上完成集成通过后，接下来会进入那个阶段	", option:"	A:外部灰度B:正式发布C:内部灰度D:创建灰度包	", out:"	参考答案：D	"},
                    {title:"	Windows系统，生成密钥后如何直接拷贝	", option:"	A:pbcopy<~/.ssh/id_rsa.pubB:xclip-selclip<~/.ssh/id_rsa.pubC:clip<~/.ssh/id_rsa.pub	", out:"	参考答案：C	"},
                    {title:"	以下哪一个是下载代码流脚本？	", option:"	A:deploy.shB:build.shC:mkview.shD:ccupdate.sh	", out:"	参考答案：C	"},
                    {title:"	下列哪些是TCENTER中测试计划涉及的测试执行轮次	", option:"	A:sit测试B:交付测试C:预发测试D:开发自测	", out:"	参考答案：ABCD	"},
                    {title:"	关于伙伴BUG的状态	", option:"	A:DuplicateB:fixedC:WontfixD:Later	", out:"	参考答案：ABCD	"},
                    {title:"	防范敏感数据泄露，以下哪些属于敏感数据	", option:"	A:会员EMAIL、支付宝帐号B:身份证信息C:银行卡卡号D:用户个人地址、联系方式	", out:"	参考答案：ABCD	"},
                    {title:"	软件验收测试的合格通过准则是：	", option:"	A:立项审批表、需求分析文档、设计文档和编码实现一致B:性能指标全部达到要求C:软件需求分析说明书中定义的所有功能已全部实现D:验收测试文档齐全	", out:"	参考答案：ABCD	"},
                    {title:"	下面哪些是关系型数据库？	", option:"	A:MySQLB:OracleC:DB2D:RedisE:Mongodb	", out:"	参考答案：ABC	"},
                    {title:"	测试的依据	", option:"	A:技术规范B:个人能力C:安全规范D:需求说明	", out:"	参考答案：ACD	"},
                    {title:"	测试人员分析需求以后生成的文档叫系分文档	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	TCENTER是基于TESTLINK改造而成的一个基于WEB的测试管理工具	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	要充分注意软件测试中的群集现象	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	测试过程中有缺陷或想查看他人在该业务里面提交的缺陷，可以切换到 缺陷 menu，点击提交缺陷到缺陷填写页面，其中是否兼容性可以不用填写	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	黑盒测试法又叫功能测试或数据驱动测试。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	Cloudengine 启动成功后，如果Cloudengine出现相关错误会将日志打印在哪里?	", option:"	A:/home/admin/logs/cloudengine/cloudengine-boot.logB:/home/admin/logs/common-error.logC:/home/admin/logs/sofa/sofa-common-error.logD:/home/admin/logs/cloudengine/common-error.log	", out:"	参考答案：D	"},
                    {title:"	在支付宝的服务器中，更新服务器代码的命令为	", option:"	A:mkview.shB:deploy.shC:ccupdate.shD:build.sh	", out:"	参考答案：C	"},
                    {title:"	黑盒法是根据程序的（  ）来设计测试用例的	", option:"	A:内部逻辑B:功能C:输入数据D:应用范围	", out:"	参考答案：B	"},
                    {title:"	开发工程师（服务端、前端）的职责是什么	", option:"	A:系分、编码B:系分、编码、自测C:编码D:系分、编码、自测、联调	", out:"	参考答案：D	"},
                    {title:"	下面哪个单词在SQL中代表查询的意思？	", option:"	A:deleteB:selectC:updateD:insert	", out:"	参考答案：B	"},
                    {title:"	软件测试用例主要由输入数据和（  ）两部分组成	", option:"	A:预期输出结果B:测试计划C:以往测试记录分析D:测试规则	", out:"	参考答案：A	"},
                    {title:"	下面哪个单词是数据库SQL语句中排序用的？	", option:"	A:sortB:groupbyC:sequenceD:orderby	", out:"	参考答案：D	"},
                    {title:"	关于自动化测试局限性的描述，以下错误的描述有	", option:"	A:自动测试比手工测试发现的缺陷少B:自动化测试不能取代手工测试C:自动化测试对测试设计依赖性极大D:自动测试不能提高测试覆盖率	", out:"	参考答案：A	"},
                    {title:"	测试过程中，如果需要生产二维码。我们怎么产生二维码？	", option:"	A:CharlerB:fiddlerC:luna或支付宝Scheme工具D:伙伴	", out:"	参考答案：C	"},
                    {title:"	下列关于质量红线流程规范，说法不正确的是	", option:"	A:严禁发布后没有对应的回滚方案B:严禁发布后不执行线上验证C:对于影响较小或评估后无影响的线上变更，可以直接操作D:严禁代码未经测试或未经开发自测发布上线	", out:"	参考答案：C	"},
                    {title:"	aone中，缺陷无效该如何操作	", option:"	A:让开发/自己点invalid，然后closedB:让开发点won'tfix，然后自己点closedC:让开发点fix，然后自己再点closedD:直接closed缺陷	", out:"	参考答案：AB	"},
                    {title:"	aone中，提交缺陷描述需要哪些信息	", option:"	A:原因定位B:缺陷描述、复现步骤C:期望结果、实际结果D:修复意见	", out:"	参考答案：ABCD	"},
                    {title:"	支付宝设置在环境切换时应该做以下哪些动作	", option:"	A:清理缓存B:打开预发开关C:获取设备属性D:杀进程	", out:"	参考答案：AD	"},
                    {title:"	伙伴安全要求，什么阶段的包不能发到外部社交工具，只能内部交流讨论	", option:"	A:开发包B:测试包C:内灰包D:外灰包	", out:"	参考答案：ABCD	"},
                    {title:"	测试人员在测试过程中发现一处问题，如果问题影响不大，而自己又可以修改，应立即将此问题正确修改，以加快、提高开发的进程。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	质量红线通过的标准，必须都达到要求后，代码才能到待合并状态。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	缺陷的优先级和严重程度可以根据实际情况调整。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	白盒测试方法比黑盒测试方法好。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	测试支付宝客户端需要掌握bugme、应等工具的运用	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	下面哪个工具是Linux客户端连接工具	", option:"	A:SublimeB:SecureCRTC:FiddleD:NavCat	", out:"	参考答案：B	"},
                    {title:"	PD是指什么	", option:"	A:不清楚B:产品经理C:需求文档D:项目经理	", out:"	参考答案：B	"},
                    {title:"	在Linux下，如何返回home目录	", option:"	A:cd..B:cd~C:cd.D:cd-	", out:"	参考答案：B	"},
                    {title:"	有一组测试用例使得每一个被测试用例的分支覆盖至少被执行一次，它满足的覆盖标准	", option:"	A:条件覆盖B:判定覆盖C:路径覆盖D:语句覆盖	", out:"	参考答案：B	"},
                    {title:"	属于黑盒测试的方法？	", option:"	A:逻辑覆盖B:基于基本路径C:控制流D:基于用户需求测试	", out:"	参考答案：D	"},
                    {title:"	伙伴中的常用术语“日常发布”的正确解释是：	", option:"	A:对线上部分用户更新以验证新功能。B:用于集成、灰度和发布的工作空间；C:通过hotpatch修复线上紧急问题的工作空间。D:用于特殊需求发布或修复线上紧急问题的工作空间	", out:"	参考答案：B	"},
                    {title:"	伙伴客户端安装包中Daily Build包指的是？	", option:"	A:每天凌晨2点基于主集成构建的灰度包，可用于第二天的功能验证和产品验收。B:可以切换到开发、测试、预发等环境，以进行功能验证。如果没有标记为可切环境，都为不可切环境的包C:已正式发布到appstore和应用市场的包D:用于正式发布到appstore和应用市场的安装包。iOS正式包只能在越狱手机上安装	", out:"	参考答案：A	"},
                    {title:"	执行更新代码、编译、部署等操作，都需要登录服务器，进入哪个目录下？	", option:"	A:/home/admin/build/B:/home/admin/bin/C:/home/admin/sharedata/D:/home/admin/ccbin/	", out:"	参考答案：D	"},
                    {title:"	什么角色负责项目流程规范执行的监督，保证项目质量？	", option:"	A:SQAB:SCMC:测试分析D:测试人员	", out:"	参考答案：A	"},
                    {title:"	下载相应版本的支付宝客户端测试包在哪个平台上操作？	", option:"	A:阿里郎B:伙伴C:钉钉D:登录中心	", out:"	参考答案：B	"},
                    {title:"	白盒测试是根据程序的（）来选设计测试用例	", option:"	A:内部逻辑B:内部数据C:功能D:性能	", out:"	参考答案：A	"},
                    {title:"	集成申请时，必填项进行填写的字段不包括以下那个	", option:"	A:集成类型B:集成原因C:打覆盖率包D:平台类型	", out:"	参考答案：C	"},
                    {title:"	下面的工具，可以做接口测试的有几个	", option:"	A:JmeterB:postmanC:seleniumD:soapUI	", out:"	参考答案：ABD	"},
                    {title:"	支付宝客户端分为哪几类	", option:"	A:测试包B:发布包C:渠道包D:灰度包E:开发包	", out:"	参考答案：ABCD	"},
                    {title:"	下列哪些选项需要在研发文档注明	", option:"	A:可回滚，回滚方案B:可灰度，灰度方案C:可监控，监控策略D:资损防控应急处理方案	", out:"	参考答案：ABCD	"},
                    {title:"	TCENTER系统有哪些主要结构	", option:"	A:测试用例B:测试计划C:用户D:测试项目	", out:"	参考答案：BCD	"},
                    {title:"	tcenter是基于web的开发管理工具	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	某个缺陷的严重性为高，则他的优先级为高	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	集成测试计划在需求分析阶段末提交	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	交付测试阶段是在以下哪个服务器上进行测试？	", option:"	A:stable服务器B:临时开发服务器C:临时测试服务器D:SIT服务器	", out:"	参考答案：C	"},
                    {title:"	改变文件所有者的命令为	", option:"	A:chownB:catC:chmodD:touch	", out:"	参考答案：A	"},
                    {title:"	软件测试的目的是	", option:"	A:发现软件错误B:试验性运行软件C:证明软件正确D:找出软件中全部错误	", out:"	参考答案：A	"},
                    {title:"	发布中的灰度发布指的是？	", option:"	A:用于特殊需求发布或修复线上紧急问题的工作空间B:用于集成、灰度和发布的工作空间C:修复线上紧急问题的工作空间D:对线上部分用户更新以验证新功能。	", out:"	参考答案：D	"},
                    {title:"	创建支付宝账户时，选择数据环境 SIT 是（）	", option:"	A:其他环境B:沙箱环境C:稳定环境D:测试环境	", out:"	参考答案：D	"},
                    {title:"	AONE中新建配置项变更流程是：开发编辑中、开发已提交、合并前验证通过、SIT验证通过和      最后一部是？	", option:"	A:开发校验B:开发审核C:开发关闭D:结束	", out:"	参考答案：D	"},
                    {title:"	以下哪个文件记录了服务的地址信息，存放了一个服务的配置信息	", option:"	A:BuildB:UisvrC:Antx.propertiesD:Sharedata	", out:"	参考答案：C	"},
                    {title:"	下列哪些是TCENTER中对测试用例可进行的操作	", option:"	A:失败B:通过C:未完成D:添加BUG	", out:"	参考答案：ABCD	"},
                    {title:"	软件验收测试的合格通过准则是	", option:"	A:软件需求分析说明书中定义的所有功能已全部实现，性能指标全部达到要求B:验收测试文档齐全C:立项审批表、需求分析文档、设计文档和编码实现一致D:所有测试项没有残余严重问题	", out:"	参考答案：ABCD	"},
                    {title:"	AONE是蚂蚁金服用于管理项目、质量监控、发布监控为一体的综合性系统，里面包含	", option:"	A:项目质量分析B:代码权限管理C:迭代流程D:需求跟踪E:需求管理	", out:"	参考答案：ABCDE	"},
                    {title:"	下面哪些是http请求体支持的数据格式	", option:"	A:key-value对B:jsonC:form表单D:xml	", out:"	参考答案：ABCD	"},
                    {title:"	功能测试属于白盒测试的技术范畴	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	在设计测试用例时，应包括合理的应用条件和不合理的应用条件。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	测试活动需要在日常环境或者预发环境进行，也可以直接在线上进行测试	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	项目页面中主要包含，概况、任务、需求、缺陷、迭代、风险、变更、发布、更多流程、测试用例、图标、设置。其中最常用的是需求、缺陷、迭代、变更和发布。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	与设计测试用例无关的文档是	", option:"	A:设计说明书B:需求规格说明书C:源程序D:项目开发计划	", out:"	参考答案：D	"},
                    {title:"	在开发交付测试之后正确测试阶段顺序是：	", option:"	A:交付测试—功能测试—代码合并—SIT集成测试—预发布验证B:交付测试—功能测试—SIT集成测试—代码合并—预发布验证C:交付测试—代码合并—SIT集成测试—功能测试—预发布验证D:交付测试—SIT集成测试—代码合并—功能测试—预发布验证	", out:"	参考答案：A	"},
                    {title:"	下面哪个单词是数据库SQL语句中过滤重复记录的？	", option:"	A:distinctB:betweenC:existsD:any	", out:"	参考答案：A	"},
                    {title:"	哪个方法根据输出输入依赖关系设计的测试用例	", option:"	A:归纳B:路径C:因果图D:等价类	", out:"	参考答案：C	"},
                    {title:"	软件缺陷都包括什么？	", option:"	A:软件的使用未能符合客户的习惯和工作环境B:软件未达到客户需求的功能和性能C:软件出现客户需求不能容忍的错误D:软件超出客户需求的范围	", out:"	参考答案：ABCD	"},
                    {title:"	PD主要职责是了解用户和市场需求，提交需求给开发部门，产生PRD文档，通常产生文档为《系分文档》	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	发现错误是软件测试的目的。	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	等价类法和边界值着重考虑输入条件，而不考虑输入条件的各种组合，也不考虑输 入条件之间的相互制约关系。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	某次程序调试没有出现预计的结果，不可能是导致出错的原因的是：	", option:"	A:变量没有初始化B:编写的语句书写格式不规范C:循环控制出错D:代码输入有误	", out:"	参考答案：B	"},
                    {title:"	下面哪些是支付宝项目中的角色？	", option:"	A:测试人员B:项目经理C:一般开发人员D:一般开发人员E:系统分析人员	", out:"	参考答案：ABCDE	"},
                    {title:"	伙伴的后台，主要内容有一些技术文档分享、我参与的项目列表、最新DailyBuild包、我的云雀、我的常用工具。重点关心的是“研发中心”tab下的常用功能，主要模块包括	", option:"	A:发布B:我的待办C:缺陷D:变更	", out:"	参考答案：ABCD	"},
                    {title:"	Uisvr目录是存放什么文件的：	", option:"	A:vm文件B:js文件C:java文件D:css文件	", out:"	参考答案：ABD	"},
                    {title:"	下面哪些单词是数据库SQL语句中的子查询中的关键字？	", option:"	A:tableB:allC:existsD:in	", out:"	参考答案：BCD	"},
                    {title:"	测试计划是与AONE里的项目管理通过项目ID关联起来的，项目ID必须正确，项目完成时间必须与实际一致。	", option:"	是不是	", out:"	参考答案：是	"},
                    {title:"	测试计划不需要与AONE里的项目管理通过项目ID关联起来的	", option:"	是不是	", out:"	参考答案：不是	"},
                    {title:"	用边界值分析法，假定 1<X<100 ，那么 X 在测试中应该取的边界值是 ______	", option:"	A:X=1，X=100B:X=2，X=99C:X=O，X=101D:X=0，X=1，X=100，X=101	", out:"	参考答案：B	"},
                    {title:"	测试执行轮次在哪里设置	", option:"	A:测试计划B:测试需求C:测试任务D:测试分析	", out:"	参考答案：A	"},
                    {title:"	怎么查看日志？	", option:"	A:ls-bB:ls-fC:ls-cD:ls-ah	", out:"	参考答案：D	"},
                    {title:"	在SQL语句，统计查询结果的数量是用什么关键字？	", option:"	A:likeB:countC:sumD:limit	", out:"	参考答案：B	"},
                    {title:"	测试设计员的职责有：______ ①制定测试计划   ②设计测试用例    ③设计测试过程、脚本    ④评估测试活动	", option:"	A:①③B:①④C:②③D:以上全是	", out:"	参考答案：C	"},
                    {title:"	测试人员在测试过程中发现一处问题，如果问题影响不大，而自己又可以修改，应 立即将此问题正确修改，以加快、提高开发的进程。	", option:"	是不是	", out:"	参考答案：不是	"}

        			];
        $(function(){
        　　$("#butGet").click(function(){
                var flag = 1;
                var textIn = $("#textIn").val();
                if(textIn == ""){
                    alert("请输入题目，再查询");
                    return 0;
                }
                $("#pOut").find("p").remove();
                for(var i in tests){
                    if(tests[i].title.indexOf(textIn) > 0){
                        flag = 0;
                        $("#pOut").append("<p>题目："+tests[i].title+"</p>")
                        .append("<p>选项："+tests[i].option+"</p>")
                        .append("<p>"+tests[i].out+"</p>");
                    }
                }
                if(flag){
                    alert("未查询到你输入的题目，请简化部分题干。如还是查询不到说明题库无参考答案。");
                    return 0;
                }
            })
        });
    </script>

</head>
<body>
<h2>搜索到的题目过多，请精确查询输入</h2>
<input id="textIn" style="width: 358px; ">
<input type="submit" value="查询" id="butGet">
<P id="pOut"></p>
</body>
</html>
